// AUTOGENERATED FILE DO NOT EDIT!
// This file was generated by script

/**
 * @typedef {object} ActivityCategory
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ActivityCategoryQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ActivityCursorPage
 * @property {boolean} reverse
 * @property {string} beforeCursor
 * @property {string} afterCursor
 * @property {boolean} hasBefore
 * @property {boolean} hasAfter
 * @property {ActivityItem} activities
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ActivityCursorPageQueryFields
 * @property {*} reverse
 * @property {*} beforeCursor
 * @property {*} afterCursor
 * @property {*} hasBefore
 * @property {*} hasAfter
 * @property {ActivityItemQueryFields} activities
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ActivityItem
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ActivityItemQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} Agile
 * @property {string} name
 * @property {User} owner
 * @property {UserGroup} visibleFor
 * @property {boolean} visibleForProjectBased
 * @property {UserGroup} updateableBy
 * @property {boolean} updateableByProjectBased
 * @property {boolean} orphansAtTheTop
 * @property {boolean} hideOrphansSwimlane
 * @property {CustomField} estimationField
 * @property {CustomField} originalEstimationField
 * @property {Array<Project>} projects
 * @property {Array<Sprint>} sprints
 * @property {Sprint} currentSprint
 * @property {ColumnSettings} columnSettings
 * @property {SwimlaneSettings} swimlaneSettings
 * @property {SprintsSettings} sprintsSettings
 * @property {ColorCoding} colorCoding
 * @property {AgileStatus} status
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} AgileQueryFields
 * @property {*} name
 * @property {UserQueryFields} owner
 * @property {UserGroupQueryFields} visibleFor
 * @property {*} visibleForProjectBased
 * @property {UserGroupQueryFields} updateableBy
 * @property {*} updateableByProjectBased
 * @property {*} orphansAtTheTop
 * @property {*} hideOrphansSwimlane
 * @property {CustomFieldQueryFields} estimationField
 * @property {CustomFieldQueryFields} originalEstimationField
 * @property {ProjectQueryFields} projects
 * @property {SprintQueryFields} sprints
 * @property {SprintQueryFields} currentSprint
 * @property {ColumnSettingsQueryFields} columnSettings
 * @property {SwimlaneSettingsQueryFields} swimlaneSettings
 * @property {SprintsSettingsQueryFields} sprintsSettings
 * @property {ColorCodingQueryFields} colorCoding
 * @property {AgileStatusQueryFields} status
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} AgileColumn
 * @property {string} presentation
 * @property {boolean} isResolved
 * @property {number} ordinal
 * @property {ColumnSettings} parent
 * @property {WIPLimit} wipLimit
 * @property {Array<AgileColumnFieldValue>} fieldValues
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} AgileColumnQueryFields
 * @property {*} presentation
 * @property {*} isResolved
 * @property {*} ordinal
 * @property {ColumnSettingsQueryFields} parent
 * @property {WIPLimitQueryFields} wipLimit
 * @property {AgileColumnFieldValueQueryFields} fieldValues
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(DatabaseAttributeValue|object)} AgileColumnFieldValue
 */

/**
 * @typedef {(DatabaseAttributeValueQueryFields|object)} AgileColumnFieldValueQueryFields
 */

/**
 * @typedef {object} AgileStatus
 * @property {boolean} valid
 * @property {boolean} hasJobs
 * @property {string} errors
 * @property {string} warnings
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} AgileStatusQueryFields
 * @property {*} valid
 * @property {*} hasJobs
 * @property {*} errors
 * @property {*} warnings
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} AppearanceSettings
 * @property {TimeZoneDescriptor} timeZone
 * @property {DateFormatDescriptor} dateFieldFormat
 * @property {Logo} logo
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} AppearanceSettingsQueryFields
 * @property {TimeZoneDescriptorQueryFields} timeZone
 * @property {DateFormatDescriptorQueryFields} dateFieldFormat
 * @property {LogoQueryFields} logo
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} AttachmentActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemQueryFields|object)} AttachmentActivityItemQueryFields
 */

/**
 * @typedef {(SwimlaneSettings|object)} AttributeBasedSwimlaneSettings
 */

/**
 * @typedef {(SwimlaneSettingsQueryFields|object)} AttributeBasedSwimlaneSettingsQueryFields
 */

/**
 * @typedef {object} BackupError
 * @property {number} date
 * @property {string} errorMessage
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BackupErrorQueryFields
 * @property {*} date
 * @property {*} errorMessage
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} BackupFile
 * @property {string} name
 * @property {number} size
 * @property {number} creationDate
 * @property {string} link
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BackupFileQueryFields
 * @property {*} name
 * @property {*} size
 * @property {*} creationDate
 * @property {*} link
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} BackupStatus
 * @property {boolean} backupInProgress
 * @property {boolean} backupCancelled
 * @property {BackupError} backupError
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BackupStatusQueryFields
 * @property {*} backupInProgress
 * @property {*} backupCancelled
 * @property {BackupErrorQueryFields} backupError
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(Bundle)} BaseBundle
 */

/**
 * @typedef {(BundleQueryFields)} BaseBundleQueryFields
 */

/**
 * @typedef {(BaseBundle|object)} BuildBundle
 */

/**
 * @typedef {(BaseBundleQueryFields|object)} BuildBundleQueryFields
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} BuildBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsQueryFields|object)} BuildBundleCustomFieldDefaultsQueryFields
 */

/**
 * @typedef {(BundleElement|object)} BuildBundleElement
 */

/**
 * @typedef {(BundleElementQueryFields|object)} BuildBundleElementQueryFields
 */

/**
 * @typedef {(BundleProjectCustomField|object)} BuildProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldQueryFields|object)} BuildProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} Bundle
 * @property {boolean} isUpdateable
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BundleQueryFields
 * @property {*} isUpdateable
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CustomFieldDefaults)} BundleCustomFieldDefaults
 */

/**
 * @typedef {(CustomFieldDefaultsQueryFields)} BundleCustomFieldDefaultsQueryFields
 */

/**
 * @typedef {object} BundleElement
 * @property {string} name
 * @property {Bundle} bundle
 * @property {string} description
 * @property {number} ordinal
 * @property {FieldStyle} color
 * @property {boolean} hasRunningJob
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BundleElementQueryFields
 * @property {*} name
 * @property {BundleQueryFields} bundle
 * @property {*} description
 * @property {*} ordinal
 * @property {FieldStyleQueryFields} color
 * @property {*} hasRunningJob
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(ProjectCustomField)} BundleProjectCustomField
 */

/**
 * @typedef {(ProjectCustomFieldQueryFields)} BundleProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} ColorCoding
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ColorCodingQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ColumnSettings
 * @property {CustomField} field
 * @property {Array<AgileColumn>} columns
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ColumnSettingsQueryFields
 * @property {CustomFieldQueryFields} field
 * @property {AgileColumnQueryFields} columns
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CommandVisibility|object)} CommandLimitedVisibility
 */

/**
 * @typedef {(CommandVisibilityQueryFields|object)} CommandLimitedVisibilityQueryFields
 */

/**
 * @typedef {object} CommandList
 * @property {string} comment
 * @property {CommandVisibility} visibility
 * @property {string} query
 * @property {number} caret
 * @property {boolean} silent
 * @property {boolean} usesMarkdown
 * @property {string} runAs
 * @property {Array<ParsedCommand>} commands
 * @property {Array<Issue>} issues
 * @property {Array<Suggestion>} suggestions
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} CommandListQueryFields
 * @property {*} comment
 * @property {CommandVisibilityQueryFields} visibility
 * @property {*} query
 * @property {*} caret
 * @property {*} silent
 * @property {*} usesMarkdown
 * @property {*} runAs
 * @property {ParsedCommandQueryFields} commands
 * @property {IssueQueryFields} issues
 * @property {SuggestionQueryFields} suggestions
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CommandVisibility)} CommandUnlimitedVisibility
 */

/**
 * @typedef {(CommandVisibilityQueryFields)} CommandUnlimitedVisibilityQueryFields
 */

/**
 * @typedef {object} CommandVisibility
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} CommandVisibilityQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} CommentActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemQueryFields|object)} CommentActivityItemQueryFields
 */

/**
 * @typedef {(MultiValueActivityItem|object)} CommentAttachmentsActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemQueryFields|object)} CommentAttachmentsActivityItemQueryFields
 */

/**
 * @typedef {(ActivityItem)} CreatedDeletedActivityItem
 */

/**
 * @typedef {(ActivityItemQueryFields)} CreatedDeletedActivityItemQueryFields
 */

/**
 * @typedef {object} CustomField
 * @property {string} name
 * @property {string} localizedName
 * @property {FieldType} fieldType
 * @property {boolean} isAutoAttached
 * @property {boolean} isDisplayedInIssueList
 * @property {number} ordinal
 * @property {string} aliases
 * @property {CustomFieldDefaults} fieldDefaults
 * @property {boolean} hasRunningJob
 * @property {boolean} isUpdateable
 * @property {Array<ProjectCustomField>} instances
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} CustomFieldQueryFields
 * @property {*} name
 * @property {*} localizedName
 * @property {FieldTypeQueryFields} fieldType
 * @property {*} isAutoAttached
 * @property {*} isDisplayedInIssueList
 * @property {*} ordinal
 * @property {*} aliases
 * @property {CustomFieldDefaultsQueryFields} fieldDefaults
 * @property {*} hasRunningJob
 * @property {*} isUpdateable
 * @property {ProjectCustomFieldQueryFields} instances
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(ActivityItem|object)} CustomFieldActivityItem
 */

/**
 * @typedef {(ActivityItemQueryFields|object)} CustomFieldActivityItemQueryFields
 */

/**
 * @typedef {object} CustomFieldDefaults
 * @property {boolean} canBeEmpty
 * @property {string} emptyFieldText
 * @property {boolean} isPublic
 * @property {CustomField} parent
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} CustomFieldDefaultsQueryFields
 * @property {*} canBeEmpty
 * @property {*} emptyFieldText
 * @property {*} isPublic
 * @property {CustomFieldQueryFields} parent
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(FilterField|object)} CustomFilterField
 */

/**
 * @typedef {(FilterFieldQueryFields|object)} CustomFilterFieldQueryFields
 */

/**
 * @typedef {object} DatabaseAttributeValue
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DatabaseAttributeValueQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} DatabaseBackupSettings
 * @property {string} location
 * @property {number} filesToKeep
 * @property {string} cronExpression
 * @property {string} archiveFormat
 * @property {boolean} isOn
 * @property {number} availableDiskSpace
 * @property {Array<User>} notifiedUsers
 * @property {BackupStatus} backupStatus
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DatabaseBackupSettingsQueryFields
 * @property {*} location
 * @property {*} filesToKeep
 * @property {*} cronExpression
 * @property {*} archiveFormat
 * @property {*} isOn
 * @property {*} availableDiskSpace
 * @property {UserQueryFields} notifiedUsers
 * @property {BackupStatusQueryFields} backupStatus
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} DateFormatDescriptor
 * @property {string} presentation
 * @property {string} pattern
 * @property {string} datePattern
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DateFormatDescriptorQueryFields
 * @property {*} presentation
 * @property {*} pattern
 * @property {*} datePattern
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(SimpleIssueCustomField|object)} DateIssueCustomField
 */

/**
 * @typedef {(SimpleIssueCustomFieldQueryFields|object)} DateIssueCustomFieldQueryFields
 */

/**
 * @typedef {object} DuplicateVote
 * @property {Issue} issue
 * @property {User} user
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DuplicateVoteQueryFields
 * @property {IssueQueryFields} issue
 * @property {UserQueryFields} user
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} DurationValue
 * @property {number} minutes
 * @property {string} presentation
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DurationValueQueryFields
 * @property {*} minutes
 * @property {*} presentation
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} EmailSettings
 * @property {boolean} isEnabled
 * @property {string} host
 * @property {number} port
 * @property {string} mailProtocol
 * @property {boolean} anonymous
 * @property {string} login
 * @property {StorageEntry} sslKey
 * @property {string} from
 * @property {string} replyTo
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} EmailSettingsQueryFields
 * @property {*} isEnabled
 * @property {*} host
 * @property {*} port
 * @property {*} mailProtocol
 * @property {*} anonymous
 * @property {*} login
 * @property {StorageEntryQueryFields} sslKey
 * @property {*} from
 * @property {*} replyTo
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BaseBundle|object)} EnumBundle
 */

/**
 * @typedef {(BaseBundleQueryFields|object)} EnumBundleQueryFields
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} EnumBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsQueryFields|object)} EnumBundleCustomFieldDefaultsQueryFields
 */

/**
 * @typedef {(LocalizableBundleElement)} EnumBundleElement
 */

/**
 * @typedef {(LocalizableBundleElementQueryFields)} EnumBundleElementQueryFields
 */

/**
 * @typedef {(BundleProjectCustomField|object)} EnumProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldQueryFields|object)} EnumProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} ExternalIssue
 * @property {string} name
 * @property {string} url
 * @property {string} key
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ExternalIssueQueryFields
 * @property {*} name
 * @property {*} url
 * @property {*} key
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(ColorCoding|object)} FieldBasedColorCoding
 */

/**
 * @typedef {(ColorCodingQueryFields|object)} FieldBasedColorCodingQueryFields
 */

/**
 * @typedef {object} FieldStyle
 * @property {string} background
 * @property {string} foreground
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} FieldStyleQueryFields
 * @property {*} background
 * @property {*} foreground
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} FieldType
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} FieldTypeQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} FilterField
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} FilterFieldQueryFields
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} GeneralUserProfile
 * @property {DateFormatDescriptor} dateFieldFormat
 * @property {TimeZoneDescriptor} timezone
 * @property {LocaleDescriptor} locale
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} GeneralUserProfileQueryFields
 * @property {DateFormatDescriptorQueryFields} dateFieldFormat
 * @property {TimeZoneDescriptorQueryFields} timezone
 * @property {LocaleDescriptorQueryFields} locale
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} GlobalSettings
 * @property {SystemSettings} systemSettings
 * @property {NotificationSettings} notificationSettings
 * @property {RestCorsSettings} restSettings
 * @property {AppearanceSettings} appearanceSettings
 * @property {LocaleSettings} localeSettings
 * @property {License} license
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} GlobalSettingsQueryFields
 * @property {SystemSettingsQueryFields} systemSettings
 * @property {NotificationSettingsQueryFields} notificationSettings
 * @property {RestCorsSettingsQueryFields} restSettings
 * @property {AppearanceSettingsQueryFields} appearanceSettings
 * @property {LocaleSettingsQueryFields} localeSettings
 * @property {LicenseQueryFields} license
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} GlobalTimeTrackingSettings
 * @property {Array<WorkItemType>} workItemTypes
 * @property {WorkTimeSettings} workTimeSettings
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} GlobalTimeTrackingSettingsQueryFields
 * @property {WorkItemTypeQueryFields} workItemTypes
 * @property {WorkTimeSettingsQueryFields} workTimeSettings
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(ProjectCustomField|object)} GroupProjectCustomField
 */

/**
 * @typedef {(ProjectCustomFieldQueryFields|object)} GroupProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} Issue
 * @property {string} idReadable
 * @property {number} created
 * @property {number} updated
 * @property {number} resolved
 * @property {number} numberInProject
 * @property {Project} project
 * @property {string} summary
 * @property {string} description
 * @property {boolean} usesMarkdown
 * @property {string} wikifiedDescription
 * @property {User} reporter
 * @property {User} updater
 * @property {User} draftOwner
 * @property {boolean} isDraft
 * @property {Visibility} visibility
 * @property {number} votes
 * @property {Array<IssueComment>} comments
 * @property {number} commentsCount
 * @property {Array<IssueTag>} tags
 * @property {Array<IssueLink>} links
 * @property {ExternalIssue} externalIssue
 * @property {Array<IssueCustomField>} customFields
 * @property {IssueVoters} voters
 * @property {IssueWatchers} watchers
 * @property {Array<IssueAttachment>} attachments
 * @property {IssueLink} subtasks
 * @property {IssueLink} parent
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueQueryFields
 * @property {*} idReadable
 * @property {*} created
 * @property {*} updated
 * @property {*} resolved
 * @property {*} numberInProject
 * @property {ProjectQueryFields} project
 * @property {*} summary
 * @property {*} description
 * @property {*} usesMarkdown
 * @property {*} wikifiedDescription
 * @property {UserQueryFields} reporter
 * @property {UserQueryFields} updater
 * @property {UserQueryFields} draftOwner
 * @property {*} isDraft
 * @property {VisibilityQueryFields} visibility
 * @property {*} votes
 * @property {IssueCommentQueryFields} comments
 * @property {*} commentsCount
 * @property {IssueTagQueryFields} tags
 * @property {IssueLinkQueryFields} links
 * @property {ExternalIssueQueryFields} externalIssue
 * @property {IssueCustomFieldQueryFields} customFields
 * @property {IssueVotersQueryFields} voters
 * @property {IssueWatchersQueryFields} watchers
 * @property {IssueAttachmentQueryFields} attachments
 * @property {IssueLinkQueryFields} subtasks
 * @property {IssueLinkQueryFields} parent
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueAttachment
 * @property {string} name
 * @property {User} author
 * @property {number} created
 * @property {number} updated
 * @property {number} size
 * @property {string} extension
 * @property {string} charset
 * @property {string} mimeType
 * @property {string} metaData
 * @property {boolean} draft
 * @property {boolean} removed
 * @property {string} base64Content
 * @property {string} url
 * @property {Visibility} visibility
 * @property {Issue} issue
 * @property {IssueComment} comment
 * @property {string} thumbnailURL
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueAttachmentQueryFields
 * @property {*} name
 * @property {UserQueryFields} author
 * @property {*} created
 * @property {*} updated
 * @property {*} size
 * @property {*} extension
 * @property {*} charset
 * @property {*} mimeType
 * @property {*} metaData
 * @property {*} draft
 * @property {*} removed
 * @property {*} base64Content
 * @property {*} url
 * @property {VisibilityQueryFields} visibility
 * @property {IssueQueryFields} issue
 * @property {IssueCommentQueryFields} comment
 * @property {*} thumbnailURL
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(SwimlaneSettings|object)} IssueBasedSwimlaneSettings
 */

/**
 * @typedef {(SwimlaneSettingsQueryFields|object)} IssueBasedSwimlaneSettingsQueryFields
 */

/**
 * @typedef {object} IssueComment
 * @property {string} text
 * @property {boolean} usesMarkdown
 * @property {string} textPreview
 * @property {number} created
 * @property {number} updated
 * @property {User} author
 * @property {Issue} issue
 * @property {Array<IssueAttachment>} attachments
 * @property {Visibility} visibility
 * @property {boolean} deleted
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueCommentQueryFields
 * @property {*} text
 * @property {*} usesMarkdown
 * @property {*} textPreview
 * @property {*} created
 * @property {*} updated
 * @property {UserQueryFields} author
 * @property {IssueQueryFields} issue
 * @property {IssueAttachmentQueryFields} attachments
 * @property {VisibilityQueryFields} visibility
 * @property {*} deleted
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} IssueCreatedActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemQueryFields|object)} IssueCreatedActivityItemQueryFields
 */

/**
 * @typedef {object} IssueCustomField
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueCustomFieldQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueFolder
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueFolderQueryFields
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueLink
 * @property {string} direction
 * @property {IssueLinkType} linkType
 * @property {Array<Issue>} issues
 * @property {Array<Issue>} trimmedIssues
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueLinkQueryFields
 * @property {*} direction
 * @property {IssueLinkTypeQueryFields} linkType
 * @property {IssueQueryFields} issues
 * @property {IssueQueryFields} trimmedIssues
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueLinkType
 * @property {string} name
 * @property {string} localizedName
 * @property {string} sourceToTarget
 * @property {string} localizedSourceToTarget
 * @property {string} targetToSource
 * @property {string} localizedTargetToSource
 * @property {boolean} directed
 * @property {boolean} aggregation
 * @property {boolean} readOnly
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueLinkTypeQueryFields
 * @property {*} name
 * @property {*} localizedName
 * @property {*} sourceToTarget
 * @property {*} localizedSourceToTarget
 * @property {*} targetToSource
 * @property {*} localizedTargetToSource
 * @property {*} directed
 * @property {*} aggregation
 * @property {*} readOnly
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(SimpleValueActivityItem|object)} IssueResolvedActivityItem
 */

/**
 * @typedef {(SimpleValueActivityItemQueryFields|object)} IssueResolvedActivityItemQueryFields
 */

/**
 * @typedef {(WatchFolder|object)} IssueTag
 */

/**
 * @typedef {(WatchFolderQueryFields|object)} IssueTagQueryFields
 */

/**
 * @typedef {object} IssueTimeTracker
 * @property {Array<IssueWorkItem>} workItems
 * @property {boolean} enabled
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueTimeTrackerQueryFields
 * @property {IssueWorkItemQueryFields} workItems
 * @property {*} enabled
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueVoters
 * @property {boolean} hasVote
 * @property {Array<User>} original
 * @property {Array<DuplicateVote>} duplicate
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueVotersQueryFields
 * @property {*} hasVote
 * @property {UserQueryFields} original
 * @property {DuplicateVoteQueryFields} duplicate
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueWatcher
 * @property {User} user
 * @property {Issue} issue
 * @property {boolean} isStarred
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueWatcherQueryFields
 * @property {UserQueryFields} user
 * @property {IssueQueryFields} issue
 * @property {*} isStarred
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueWatchers
 * @property {boolean} hasStar
 * @property {Array<IssueWatcher>} issueWatchers
 * @property {Array<IssueWatcher>} duplicateWatchers
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueWatchersQueryFields
 * @property {*} hasStar
 * @property {IssueWatcherQueryFields} issueWatchers
 * @property {IssueWatcherQueryFields} duplicateWatchers
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueWorkItem
 * @property {User} author
 * @property {User} creator
 * @property {string} text
 * @property {string} textPreview
 * @property {WorkItemType} type
 * @property {number} created
 * @property {number} updated
 * @property {DurationValue} duration
 * @property {number} date
 * @property {Issue} issue
 * @property {boolean} usesMarkdown
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueWorkItemQueryFields
 * @property {UserQueryFields} author
 * @property {UserQueryFields} creator
 * @property {*} text
 * @property {*} textPreview
 * @property {WorkItemTypeQueryFields} type
 * @property {*} created
 * @property {*} updated
 * @property {DurationValueQueryFields} duration
 * @property {*} date
 * @property {IssueQueryFields} issue
 * @property {*} usesMarkdown
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} JabberSettings
 * @property {boolean} isEnabled
 * @property {string} host
 * @property {number} port
 * @property {string} login
 * @property {string} serviceName
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} JabberSettingsQueryFields
 * @property {*} isEnabled
 * @property {*} host
 * @property {*} port
 * @property {*} login
 * @property {*} serviceName
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} License
 * @property {string} username
 * @property {string} license
 * @property {string} error
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} LicenseQueryFields
 * @property {*} username
 * @property {*} license
 * @property {*} error
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(Visibility|object)} LimitedVisibility
 */

/**
 * @typedef {(VisibilityQueryFields|object)} LimitedVisibilityQueryFields
 */

/**
 * @typedef {(MultiValueActivityItem|object)} LinksActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemQueryFields|object)} LinksActivityItemQueryFields
 */

/**
 * @typedef {object} LocaleDescriptor
 * @property {string} locale
 * @property {string} language
 * @property {boolean} community
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} LocaleDescriptorQueryFields
 * @property {*} locale
 * @property {*} language
 * @property {*} community
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} LocaleSettings
 * @property {LocaleDescriptor} locale
 * @property {boolean} isRTL
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} LocaleSettingsQueryFields
 * @property {LocaleDescriptorQueryFields} locale
 * @property {*} isRTL
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BundleElement|object)} LocalizableBundleElement
 */

/**
 * @typedef {(BundleElementQueryFields|object)} LocalizableBundleElementQueryFields
 */

/**
 * @typedef {object} Logo
 * @property {string} url
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} LogoQueryFields
 * @property {*} url
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(User)} Me
 */

/**
 * @typedef {(UserQueryFields)} MeQueryFields
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiBuildIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldQueryFields|object)} MultiBuildIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiEnumIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldQueryFields|object)} MultiEnumIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiGroupIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldQueryFields|object)} MultiGroupIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiOwnedIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldQueryFields|object)} MultiOwnedIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiUserIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldQueryFields|object)} MultiUserIssueCustomFieldQueryFields
 */

/**
 * @typedef {(ActivityItem)} MultiValueActivityItem
 */

/**
 * @typedef {(ActivityItemQueryFields)} MultiValueActivityItemQueryFields
 */

/**
 * @typedef {(IssueCustomField|object)} DatabaseMultiValueIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldQueryFields|object)} DatabaseMultiValueIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiVersionIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldQueryFields|object)} MultiVersionIssueCustomFieldQueryFields
 */

/**
 * @typedef {object} NotificationSettings
 * @property {EmailSettings} emailSettings
 * @property {JabberSettings} jabberSettings
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} NotificationSettingsQueryFields
 * @property {EmailSettingsQueryFields} emailSettings
 * @property {JabberSettingsQueryFields} jabberSettings
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} NotificationsUserProfile
 * @property {boolean} notifyOnOwnChanges
 * @property {boolean} jabberNotificationsEnabled
 * @property {boolean} emailNotificationsEnabled
 * @property {boolean} mentionNotificationsEnabled
 * @property {boolean} duplicateClusterNotificationsEnabled
 * @property {boolean} mailboxIntegrationNotificationsEnabled
 * @property {boolean} usePlainTextEmails
 * @property {boolean} autoWatchOnComment
 * @property {boolean} autoWatchOnVote
 * @property {boolean} autoWatchOnUpdate
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} NotificationsUserProfileQueryFields
 * @property {*} notifyOnOwnChanges
 * @property {*} jabberNotificationsEnabled
 * @property {*} emailNotificationsEnabled
 * @property {*} mentionNotificationsEnabled
 * @property {*} duplicateClusterNotificationsEnabled
 * @property {*} mailboxIntegrationNotificationsEnabled
 * @property {*} usePlainTextEmails
 * @property {*} autoWatchOnComment
 * @property {*} autoWatchOnVote
 * @property {*} autoWatchOnUpdate
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} OnlineUsers
 * @property {number} users
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} OnlineUsersQueryFields
 * @property {*} users
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BaseBundle|object)} OwnedBundle
 */

/**
 * @typedef {(BaseBundleQueryFields|object)} OwnedBundleQueryFields
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} OwnedBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsQueryFields|object)} OwnedBundleCustomFieldDefaultsQueryFields
 */

/**
 * @typedef {(BundleElement|object)} OwnedBundleElement
 */

/**
 * @typedef {(BundleElementQueryFields|object)} OwnedBundleElementQueryFields
 */

/**
 * @typedef {(BundleProjectCustomField|object)} OwnedProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldQueryFields|object)} OwnedProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} ParsedCommand
 * @property {string} description
 * @property {boolean} error
 * @property {boolean} delete
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ParsedCommandQueryFields
 * @property {*} description
 * @property {*} error
 * @property {*} delete
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} PeriodFieldFormat
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} PeriodFieldFormatQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(IssueCustomField|object)} PeriodIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldQueryFields|object)} PeriodIssueCustomFieldQueryFields
 */

/**
 * @typedef {(ProjectCustomField)} PeriodProjectCustomField
 */

/**
 * @typedef {(ProjectCustomFieldQueryFields)} PeriodProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} PeriodValue
 * @property {number} minutes
 * @property {string} presentation
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} PeriodValueQueryFields
 * @property {*} minutes
 * @property {*} presentation
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(FilterField)} PredefinedFilterField
 */

/**
 * @typedef {(FilterFieldQueryFields)} PredefinedFilterFieldQueryFields
 */

/**
 * @typedef {(IssueFolder|object)} Project
 */

/**
 * @typedef {(IssueFolderQueryFields|object)} ProjectQueryFields
 */

/**
 * @typedef {(SingleValueActivityItem|object)} ProjectActivityItem
 */

/**
 * @typedef {(SingleValueActivityItemQueryFields|object)} ProjectActivityItemQueryFields
 */

/**
 * @typedef {(ColorCoding|object)} ProjectBasedColorCoding
 */

/**
 * @typedef {(ColorCodingQueryFields|object)} ProjectBasedColorCodingQueryFields
 */

/**
 * @typedef {object} ProjectColor
 * @property {Project} project
 * @property {FieldStyle} color
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ProjectColorQueryFields
 * @property {ProjectQueryFields} project
 * @property {FieldStyleQueryFields} color
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ProjectCustomField
 * @property {CustomField} field
 * @property {Project} project
 * @property {boolean} canBeEmpty
 * @property {string} emptyFieldText
 * @property {number} ordinal
 * @property {boolean} isPublic
 * @property {boolean} hasRunningJob
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ProjectCustomFieldQueryFields
 * @property {CustomFieldQueryFields} field
 * @property {ProjectQueryFields} project
 * @property {*} canBeEmpty
 * @property {*} emptyFieldText
 * @property {*} ordinal
 * @property {*} isPublic
 * @property {*} hasRunningJob
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ProjectTimeTrackingSettings
 * @property {boolean} enabled
 * @property {ProjectCustomField} estimate
 * @property {ProjectCustomField} timeSpent
 * @property {Array<WorkItemType>} workItemTypes
 * @property {Project} project
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ProjectTimeTrackingSettingsQueryFields
 * @property {*} enabled
 * @property {ProjectCustomFieldQueryFields} estimate
 * @property {ProjectCustomFieldQueryFields} timeSpent
 * @property {WorkItemTypeQueryFields} workItemTypes
 * @property {ProjectQueryFields} project
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} RestCorsSettings
 * @property {string} allowedOrigins
 * @property {boolean} allowAllOrigins
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} RestCorsSettingsQueryFields
 * @property {*} allowedOrigins
 * @property {*} allowAllOrigins
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(WatchFolder|object)} SavedQuery
 */

/**
 * @typedef {(WatchFolderQueryFields|object)} SavedQueryQueryFields
 */

/**
 * @typedef {(IssueCustomField|object)} SimpleIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldQueryFields|object)} SimpleIssueCustomFieldQueryFields
 */

/**
 * @typedef {(ProjectCustomField)} SimpleProjectCustomField
 */

/**
 * @typedef {(ProjectCustomFieldQueryFields)} SimpleProjectCustomFieldQueryFields
 */

/**
 * @typedef {(SingleValueActivityItem|object)} SimpleValueActivityItem
 */

/**
 * @typedef {(SingleValueActivityItemQueryFields|object)} SimpleValueActivityItemQueryFields
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleBuildIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldQueryFields|object)} SingleBuildIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleEnumIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldQueryFields|object)} SingleEnumIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleGroupIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldQueryFields|object)} SingleGroupIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleOwnedIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldQueryFields|object)} SingleOwnedIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleUserIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldQueryFields|object)} SingleUserIssueCustomFieldQueryFields
 */

/**
 * @typedef {(ActivityItem)} SingleValueActivityItem
 */

/**
 * @typedef {(ActivityItemQueryFields)} SingleValueActivityItemQueryFields
 */

/**
 * @typedef {(IssueCustomField|object)} DatabaseSingleValueIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldQueryFields|object)} DatabaseSingleValueIssueCustomFieldQueryFields
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleVersionIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldQueryFields|object)} SingleVersionIssueCustomFieldQueryFields
 */

/**
 * @typedef {object} Sprint
 * @property {Agile} agile
 * @property {string} name
 * @property {string} goal
 * @property {number} start
 * @property {number} finish
 * @property {boolean} archived
 * @property {boolean} isDefault
 * @property {Array<Issue>} issues
 * @property {number} unresolvedIssuesCount
 * @property {Sprint} previousSprint
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SprintQueryFields
 * @property {AgileQueryFields} agile
 * @property {*} name
 * @property {*} goal
 * @property {*} start
 * @property {*} finish
 * @property {*} archived
 * @property {*} isDefault
 * @property {IssueQueryFields} issues
 * @property {*} unresolvedIssuesCount
 * @property {SprintQueryFields} previousSprint
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(MultiValueActivityItem|object)} SprintActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemQueryFields|object)} SprintActivityItemQueryFields
 */

/**
 * @typedef {object} SprintsSettings
 * @property {boolean} isExplicit
 * @property {boolean} cardOnSeveralSprints
 * @property {Sprint} defaultSprint
 * @property {boolean} disableSprints
 * @property {string} explicitQuery
 * @property {CustomField} sprintSyncField
 * @property {boolean} hideSubtasksOfCards
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SprintsSettingsQueryFields
 * @property {*} isExplicit
 * @property {*} cardOnSeveralSprints
 * @property {SprintQueryFields} defaultSprint
 * @property {*} disableSprints
 * @property {*} explicitQuery
 * @property {CustomFieldQueryFields} sprintSyncField
 * @property {*} hideSubtasksOfCards
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BaseBundle|object)} StateBundle
 */

/**
 * @typedef {(BaseBundleQueryFields|object)} StateBundleQueryFields
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} StateBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsQueryFields|object)} StateBundleCustomFieldDefaultsQueryFields
 */

/**
 * @typedef {(LocalizableBundleElement|object)} StateBundleElement
 */

/**
 * @typedef {(LocalizableBundleElementQueryFields|object)} StateBundleElementQueryFields
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} StateIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldQueryFields|object)} StateIssueCustomFieldQueryFields
 */

/**
 * @typedef {(BundleProjectCustomField|object)} StateProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldQueryFields|object)} StateProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} StorageEntry
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} StorageEntryQueryFields
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} Suggestion
 * @property {number} completionStart
 * @property {number} completionEnd
 * @property {number} matchingStart
 * @property {number} matchingEnd
 * @property {number} caret
 * @property {string} description
 * @property {string} option
 * @property {string} prefix
 * @property {string} suffix
 * @property {string} group
 * @property {string} icon
 * @property {string} auxiliaryIcon
 * @property {string} className
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SuggestionQueryFields
 * @property {*} completionStart
 * @property {*} completionEnd
 * @property {*} matchingStart
 * @property {*} matchingEnd
 * @property {*} caret
 * @property {*} description
 * @property {*} option
 * @property {*} prefix
 * @property {*} suffix
 * @property {*} group
 * @property {*} icon
 * @property {*} auxiliaryIcon
 * @property {*} className
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(DatabaseAttributeValue|object)} SwimlaneEntityAttributeValue
 */

/**
 * @typedef {(DatabaseAttributeValueQueryFields|object)} SwimlaneEntityAttributeValueQueryFields
 */

/**
 * @typedef {object} SwimlaneSettings
 * @property {boolean} enabled
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SwimlaneSettingsQueryFields
 * @property {*} enabled
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} SwimlaneValue
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SwimlaneValueQueryFields
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} SystemSettings
 * @property {string} baseUrl
 * @property {number} maxUploadFileSize
 * @property {number} maxExportItems
 * @property {string} administratorEmail
 * @property {boolean} allowStatisticsCollection
 * @property {boolean} isApplicationReadOnly
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SystemSettingsQueryFields
 * @property {*} baseUrl
 * @property {*} maxUploadFileSize
 * @property {*} maxExportItems
 * @property {*} administratorEmail
 * @property {*} allowStatisticsCollection
 * @property {*} isApplicationReadOnly
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(MultiValueActivityItem|object)} TagsActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemQueryFields|object)} TagsActivityItemQueryFields
 */

/**
 * @typedef {object} Telemetry
 * @property {string} installationFolder
 * @property {string} databaseLocation
 * @property {string} logsLocation
 * @property {number} availableProcessors
 * @property {string} availableMemory
 * @property {string} allocatedMemory
 * @property {string} usedMemory
 * @property {string} uptime
 * @property {number} startedTime
 * @property {number} databaseBackgroundThreads
 * @property {number} pendingAsyncJobs
 * @property {number} cachedResultsCountInDBQueriesCache
 * @property {string} databaseQueriesCacheHitRate
 * @property {string} blobStringsCacheHitRate
 * @property {number} totalTransactions
 * @property {string} transactionsPerSecond
 * @property {string} requestsPerSecond
 * @property {string} databaseSize
 * @property {string} fullDatabaseSize
 * @property {string} textIndexSize
 * @property {OnlineUsers} onlineUsers
 * @property {number} reportCalculatorThreads
 * @property {number} notificationAnalyzerThreads
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} TelemetryQueryFields
 * @property {*} installationFolder
 * @property {*} databaseLocation
 * @property {*} logsLocation
 * @property {*} availableProcessors
 * @property {*} availableMemory
 * @property {*} allocatedMemory
 * @property {*} usedMemory
 * @property {*} uptime
 * @property {*} startedTime
 * @property {*} databaseBackgroundThreads
 * @property {*} pendingAsyncJobs
 * @property {*} cachedResultsCountInDBQueriesCache
 * @property {*} databaseQueriesCacheHitRate
 * @property {*} blobStringsCacheHitRate
 * @property {*} totalTransactions
 * @property {*} transactionsPerSecond
 * @property {*} requestsPerSecond
 * @property {*} databaseSize
 * @property {*} fullDatabaseSize
 * @property {*} textIndexSize
 * @property {OnlineUsersQueryFields} onlineUsers
 * @property {*} reportCalculatorThreads
 * @property {*} notificationAnalyzerThreads
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CustomFieldActivityItem|object)} TextCustomFieldActivityItem
 */

/**
 * @typedef {(CustomFieldActivityItemQueryFields|object)} TextCustomFieldActivityItemQueryFields
 */

/**
 * @typedef {object} TextFieldValue
 * @property {string} text
 * @property {string} markdownText
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} TextFieldValueQueryFields
 * @property {*} text
 * @property {*} markdownText
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(IssueCustomField|object)} TextIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldQueryFields|object)} TextIssueCustomFieldQueryFields
 */

/**
 * @typedef {(SimpleValueActivityItem|object)} TextMarkupActivityItem
 */

/**
 * @typedef {(SimpleValueActivityItemQueryFields|object)} TextMarkupActivityItemQueryFields
 */

/**
 * @typedef {(SimpleProjectCustomField)} TextProjectCustomField
 */

/**
 * @typedef {(SimpleProjectCustomFieldQueryFields)} TextProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} TimeTrackingUserProfile
 * @property {PeriodFieldFormat} periodFormat
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} TimeTrackingUserProfileQueryFields
 * @property {PeriodFieldFormatQueryFields} periodFormat
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} TimeZoneDescriptor
 * @property {string} presentation
 * @property {number} offset
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} TimeZoneDescriptorQueryFields
 * @property {*} presentation
 * @property {*} offset
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(Visibility)} UnlimitedVisibility
 */

/**
 * @typedef {(VisibilityQueryFields)} UnlimitedVisibilityQueryFields
 */

/**
 * @typedef {object} User
 * @property {string} login
 * @property {string} fullName
 * @property {string} email
 * @property {string} jabberAccountName
 * @property {string} ringId
 * @property {boolean} guest
 * @property {boolean} online
 * @property {boolean} banned
 * @property {Array<IssueTag>} tags
 * @property {Array<SavedQuery>} savedQueries
 * @property {string} avatarUrl
 * @property {object} profiles
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} UserQueryFields
 * @property {*} login
 * @property {*} fullName
 * @property {*} email
 * @property {*} jabberAccountName
 * @property {*} ringId
 * @property {*} guest
 * @property {*} online
 * @property {*} banned
 * @property {IssueTagQueryFields} tags
 * @property {SavedQueryQueryFields} savedQueries
 * @property {*} avatarUrl
 * @property {object} profiles
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(Bundle|object)} UserBundle
 */

/**
 * @typedef {(BundleQueryFields|object)} UserBundleQueryFields
 */

/**
 * @typedef {(CustomFieldDefaults|object)} UserCustomFieldDefaults
 */

/**
 * @typedef {(CustomFieldDefaultsQueryFields|object)} UserCustomFieldDefaultsQueryFields
 */

/**
 * @typedef {object} UserGroup
 * @property {string} name
 * @property {string} ringId
 * @property {number} usersCount
 * @property {string} icon
 * @property {boolean} allUsersGroup
 * @property {Project} teamForProject
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} UserGroupQueryFields
 * @property {*} name
 * @property {*} ringId
 * @property {*} usersCount
 * @property {*} icon
 * @property {*} allUsersGroup
 * @property {ProjectQueryFields} teamForProject
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BundleProjectCustomField|object)} UserProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldQueryFields|object)} UserProjectCustomFieldQueryFields
 */

/**
 * @typedef {(SimpleValueActivityItem|object)} UsesMarkupActivityItem
 */

/**
 * @typedef {(SimpleValueActivityItemQueryFields|object)} UsesMarkupActivityItemQueryFields
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} VcsChangeActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemQueryFields|object)} VcsChangeActivityItemQueryFields
 */

/**
 * @typedef {(User|object)} VcsUnresolvedUser
 */

/**
 * @typedef {(UserQueryFields|object)} VcsUnresolvedUserQueryFields
 */

/**
 * @typedef {(BaseBundle|object)} VersionBundle
 */

/**
 * @typedef {(BaseBundleQueryFields|object)} VersionBundleQueryFields
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} VersionBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsQueryFields|object)} VersionBundleCustomFieldDefaultsQueryFields
 */

/**
 * @typedef {(BundleElement|object)} VersionBundleElement
 */

/**
 * @typedef {(BundleElementQueryFields|object)} VersionBundleElementQueryFields
 */

/**
 * @typedef {(BundleProjectCustomField|object)} VersionProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldQueryFields|object)} VersionProjectCustomFieldQueryFields
 */

/**
 * @typedef {object} Visibility
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} VisibilityQueryFields
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(MultiValueActivityItem|object)} VisibilityActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemQueryFields|object)} VisibilityActivityItemQueryFields
 */

/**
 * @typedef {(VisibilityActivityItem|object)} VisibilityGroupActivityItem
 */

/**
 * @typedef {(VisibilityActivityItemQueryFields|object)} VisibilityGroupActivityItemQueryFields
 */

/**
 * @typedef {(VisibilityActivityItem|object)} VisibilityUserActivityItem
 */

/**
 * @typedef {(VisibilityActivityItemQueryFields|object)} VisibilityUserActivityItemQueryFields
 */

/**
 * @typedef {(MultiValueActivityItem|object)} VotersActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemQueryFields|object)} VotersActivityItemQueryFields
 */

/**
 * @typedef {object} WIPLimit
 * @property {number} max
 * @property {number} min
 * @property {AgileColumn} column
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} WIPLimitQueryFields
 * @property {*} max
 * @property {*} min
 * @property {AgileColumnQueryFields} column
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(IssueFolder|object)} WatchFolder
 */

/**
 * @typedef {(IssueFolderQueryFields|object)} WatchFolderQueryFields
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} WorkItemActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemQueryFields|object)} WorkItemActivityItemQueryFields
 */

/**
 * @typedef {(SingleValueActivityItem|object)} WorkItemAuthorActivityItem
 */

/**
 * @typedef {(SingleValueActivityItemQueryFields|object)} WorkItemAuthorActivityItemQueryFields
 */

/**
 * @typedef {(SingleValueActivityItem|object)} WorkItemDurationActivityItem
 */

/**
 * @typedef {(SingleValueActivityItemQueryFields|object)} WorkItemDurationActivityItemQueryFields
 */

/**
 * @typedef {object} WorkItemType
 * @property {string} name
 * @property {boolean} autoAttached
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} WorkItemTypeQueryFields
 * @property {*} name
 * @property {*} autoAttached
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(MultiValueActivityItem|object)} WorkItemTypeActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemQueryFields|object)} WorkItemTypeActivityItemQueryFields
 */

/**
 * @typedef {object} WorkTimeSettings
 * @property {number} minutesADay
 * @property {number} workDays
 * @property {number} firstDayOfWeek
 * @property {number} daysAWeek
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} WorkTimeSettingsQueryFields
 * @property {*} minutesADay
 * @property {*} workDays
 * @property {*} firstDayOfWeek
 * @property {*} daysAWeek
 * @property {*} id
 * @property {*} $type
 */