// AUTOGENERATED FILE DO NOT EDIT!
// This file was generated by script

/**
 * @typedef {object} ActivityCategory
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ActivityCategoryShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ActivityCursorPage
 * @property {boolean} reverse
 * @property {string} beforeCursor
 * @property {string} afterCursor
 * @property {boolean} hasBefore
 * @property {boolean} hasAfter
 * @property {ActivityItem} activities
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ActivityCursorPageShape
 * @property {*} reverse
 * @property {*} beforeCursor
 * @property {*} afterCursor
 * @property {*} hasBefore
 * @property {*} hasAfter
 * @property {ActivityItemShape} activities
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ActivityItem
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ActivityItemShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} Agile
 * @property {string} name
 * @property {User} owner
 * @property {UserGroup} visibleFor
 * @property {boolean} visibleForProjectBased
 * @property {UserGroup} updateableBy
 * @property {boolean} updateableByProjectBased
 * @property {boolean} orphansAtTheTop
 * @property {boolean} hideOrphansSwimlane
 * @property {CustomField} estimationField
 * @property {CustomField} originalEstimationField
 * @property {Array<Project>} projects
 * @property {Array<Sprint>} sprints
 * @property {Sprint} currentSprint
 * @property {ColumnSettings} columnSettings
 * @property {SwimlaneSettings} swimlaneSettings
 * @property {SprintsSettings} sprintsSettings
 * @property {ColorCoding} colorCoding
 * @property {AgileStatus} status
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} AgileShape
 * @property {*} name
 * @property {UserShape} owner
 * @property {UserGroupShape} visibleFor
 * @property {*} visibleForProjectBased
 * @property {UserGroupShape} updateableBy
 * @property {*} updateableByProjectBased
 * @property {*} orphansAtTheTop
 * @property {*} hideOrphansSwimlane
 * @property {CustomFieldShape} estimationField
 * @property {CustomFieldShape} originalEstimationField
 * @property {ProjectShape} projects
 * @property {SprintShape} sprints
 * @property {SprintShape} currentSprint
 * @property {ColumnSettingsShape} columnSettings
 * @property {SwimlaneSettingsShape} swimlaneSettings
 * @property {SprintsSettingsShape} sprintsSettings
 * @property {ColorCodingShape} colorCoding
 * @property {AgileStatusShape} status
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} AgileColumn
 * @property {string} presentation
 * @property {boolean} isResolved
 * @property {number} ordinal
 * @property {ColumnSettings} parent
 * @property {WIPLimit} wipLimit
 * @property {Array<AgileColumnFieldValue>} fieldValues
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} AgileColumnShape
 * @property {*} presentation
 * @property {*} isResolved
 * @property {*} ordinal
 * @property {ColumnSettingsShape} parent
 * @property {WIPLimitShape} wipLimit
 * @property {AgileColumnFieldValueShape} fieldValues
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(DatabaseAttributeValue|object)} AgileColumnFieldValue
 */

/**
 * @typedef {(DatabaseAttributeValueShape|object)} AgileColumnFieldValueShape
 */

/**
 * @typedef {object} AgileStatus
 * @property {boolean} valid
 * @property {boolean} hasJobs
 * @property {string} errors
 * @property {string} warnings
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} AgileStatusShape
 * @property {*} valid
 * @property {*} hasJobs
 * @property {*} errors
 * @property {*} warnings
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} AppearanceSettings
 * @property {TimeZoneDescriptor} timeZone
 * @property {DateFormatDescriptor} dateFieldFormat
 * @property {Logo} logo
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} AppearanceSettingsShape
 * @property {TimeZoneDescriptorShape} timeZone
 * @property {DateFormatDescriptorShape} dateFieldFormat
 * @property {LogoShape} logo
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} AttachmentActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemShape|object)} AttachmentActivityItemShape
 */

/**
 * @typedef {(SwimlaneSettings|object)} AttributeBasedSwimlaneSettings
 */

/**
 * @typedef {(SwimlaneSettingsShape|object)} AttributeBasedSwimlaneSettingsShape
 */

/**
 * @typedef {object} BackupError
 * @property {number} date
 * @property {string} errorMessage
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BackupErrorShape
 * @property {*} date
 * @property {*} errorMessage
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} BackupFile
 * @property {string} name
 * @property {number} size
 * @property {number} creationDate
 * @property {string} link
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BackupFileShape
 * @property {*} name
 * @property {*} size
 * @property {*} creationDate
 * @property {*} link
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} BackupStatus
 * @property {boolean} backupInProgress
 * @property {boolean} backupCancelled
 * @property {BackupError} backupError
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BackupStatusShape
 * @property {*} backupInProgress
 * @property {*} backupCancelled
 * @property {BackupErrorShape} backupError
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(Bundle)} BaseBundle
 */

/**
 * @typedef {(BundleShape)} BaseBundleShape
 */

/**
 * @typedef {(BaseBundle|object)} BuildBundle
 */

/**
 * @typedef {(BaseBundleShape|object)} BuildBundleShape
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} BuildBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsShape|object)} BuildBundleCustomFieldDefaultsShape
 */

/**
 * @typedef {(BundleElement|object)} BuildBundleElement
 */

/**
 * @typedef {(BundleElementShape|object)} BuildBundleElementShape
 */

/**
 * @typedef {(BundleProjectCustomField|object)} BuildProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldShape|object)} BuildProjectCustomFieldShape
 */

/**
 * @typedef {object} Bundle
 * @property {boolean} isUpdateable
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BundleShape
 * @property {*} isUpdateable
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CustomFieldDefaults)} BundleCustomFieldDefaults
 */

/**
 * @typedef {(CustomFieldDefaultsShape)} BundleCustomFieldDefaultsShape
 */

/**
 * @typedef {object} BundleElement
 * @property {string} name
 * @property {Bundle} bundle
 * @property {string} description
 * @property {number} ordinal
 * @property {FieldStyle} color
 * @property {boolean} hasRunningJob
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} BundleElementShape
 * @property {*} name
 * @property {BundleShape} bundle
 * @property {*} description
 * @property {*} ordinal
 * @property {FieldStyleShape} color
 * @property {*} hasRunningJob
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(ProjectCustomField)} BundleProjectCustomField
 */

/**
 * @typedef {(ProjectCustomFieldShape)} BundleProjectCustomFieldShape
 */

/**
 * @typedef {object} ColorCoding
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ColorCodingShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ColumnSettings
 * @property {CustomField} field
 * @property {Array<AgileColumn>} columns
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ColumnSettingsShape
 * @property {CustomFieldShape} field
 * @property {AgileColumnShape} columns
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CommandVisibility|object)} CommandLimitedVisibility
 */

/**
 * @typedef {(CommandVisibilityShape|object)} CommandLimitedVisibilityShape
 */

/**
 * @typedef {object} CommandList
 * @property {string} comment
 * @property {CommandVisibility} visibility
 * @property {string} query
 * @property {number} caret
 * @property {boolean} silent
 * @property {boolean} usesMarkdown
 * @property {string} runAs
 * @property {Array<ParsedCommand>} commands
 * @property {Array<Issue>} issues
 * @property {Array<Suggestion>} suggestions
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} CommandListShape
 * @property {*} comment
 * @property {CommandVisibilityShape} visibility
 * @property {*} query
 * @property {*} caret
 * @property {*} silent
 * @property {*} usesMarkdown
 * @property {*} runAs
 * @property {ParsedCommandShape} commands
 * @property {IssueShape} issues
 * @property {SuggestionShape} suggestions
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CommandVisibility)} CommandUnlimitedVisibility
 */

/**
 * @typedef {(CommandVisibilityShape)} CommandUnlimitedVisibilityShape
 */

/**
 * @typedef {object} CommandVisibility
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} CommandVisibilityShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} CommentActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemShape|object)} CommentActivityItemShape
 */

/**
 * @typedef {(MultiValueActivityItem|object)} CommentAttachmentsActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemShape|object)} CommentAttachmentsActivityItemShape
 */

/**
 * @typedef {(ActivityItem)} CreatedDeletedActivityItem
 */

/**
 * @typedef {(ActivityItemShape)} CreatedDeletedActivityItemShape
 */

/**
 * @typedef {object} CustomField
 * @property {string} name
 * @property {string} localizedName
 * @property {FieldType} fieldType
 * @property {boolean} isAutoAttached
 * @property {boolean} isDisplayedInIssueList
 * @property {number} ordinal
 * @property {string} aliases
 * @property {CustomFieldDefaults} fieldDefaults
 * @property {boolean} hasRunningJob
 * @property {boolean} isUpdateable
 * @property {Array<ProjectCustomField>} instances
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} CustomFieldShape
 * @property {*} name
 * @property {*} localizedName
 * @property {FieldTypeShape} fieldType
 * @property {*} isAutoAttached
 * @property {*} isDisplayedInIssueList
 * @property {*} ordinal
 * @property {*} aliases
 * @property {CustomFieldDefaultsShape} fieldDefaults
 * @property {*} hasRunningJob
 * @property {*} isUpdateable
 * @property {ProjectCustomFieldShape} instances
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(ActivityItem|object)} CustomFieldActivityItem
 */

/**
 * @typedef {(ActivityItemShape|object)} CustomFieldActivityItemShape
 */

/**
 * @typedef {object} CustomFieldDefaults
 * @property {boolean} canBeEmpty
 * @property {string} emptyFieldText
 * @property {boolean} isPublic
 * @property {CustomField} parent
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} CustomFieldDefaultsShape
 * @property {*} canBeEmpty
 * @property {*} emptyFieldText
 * @property {*} isPublic
 * @property {CustomFieldShape} parent
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(FilterField|object)} CustomFilterField
 */

/**
 * @typedef {(FilterFieldShape|object)} CustomFilterFieldShape
 */

/**
 * @typedef {object} DatabaseAttributeValue
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DatabaseAttributeValueShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} DatabaseBackupSettings
 * @property {string} location
 * @property {number} filesToKeep
 * @property {string} cronExpression
 * @property {string} archiveFormat
 * @property {boolean} isOn
 * @property {number} availableDiskSpace
 * @property {Array<User>} notifiedUsers
 * @property {BackupStatus} backupStatus
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DatabaseBackupSettingsShape
 * @property {*} location
 * @property {*} filesToKeep
 * @property {*} cronExpression
 * @property {*} archiveFormat
 * @property {*} isOn
 * @property {*} availableDiskSpace
 * @property {UserShape} notifiedUsers
 * @property {BackupStatusShape} backupStatus
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} DateFormatDescriptor
 * @property {string} presentation
 * @property {string} pattern
 * @property {string} datePattern
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DateFormatDescriptorShape
 * @property {*} presentation
 * @property {*} pattern
 * @property {*} datePattern
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(SimpleIssueCustomField|object)} DateIssueCustomField
 */

/**
 * @typedef {(SimpleIssueCustomFieldShape|object)} DateIssueCustomFieldShape
 */

/**
 * @typedef {object} DuplicateVote
 * @property {Issue} issue
 * @property {User} user
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DuplicateVoteShape
 * @property {IssueShape} issue
 * @property {UserShape} user
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} DurationValue
 * @property {number} minutes
 * @property {string} presentation
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} DurationValueShape
 * @property {*} minutes
 * @property {*} presentation
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} EmailSettings
 * @property {boolean} isEnabled
 * @property {string} host
 * @property {number} port
 * @property {string} mailProtocol
 * @property {boolean} anonymous
 * @property {string} login
 * @property {StorageEntry} sslKey
 * @property {string} from
 * @property {string} replyTo
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} EmailSettingsShape
 * @property {*} isEnabled
 * @property {*} host
 * @property {*} port
 * @property {*} mailProtocol
 * @property {*} anonymous
 * @property {*} login
 * @property {StorageEntryShape} sslKey
 * @property {*} from
 * @property {*} replyTo
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BaseBundle|object)} EnumBundle
 */

/**
 * @typedef {(BaseBundleShape|object)} EnumBundleShape
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} EnumBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsShape|object)} EnumBundleCustomFieldDefaultsShape
 */

/**
 * @typedef {(LocalizableBundleElement)} EnumBundleElement
 */

/**
 * @typedef {(LocalizableBundleElementShape)} EnumBundleElementShape
 */

/**
 * @typedef {(BundleProjectCustomField|object)} EnumProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldShape|object)} EnumProjectCustomFieldShape
 */

/**
 * @typedef {object} ExternalIssue
 * @property {string} name
 * @property {string} url
 * @property {string} key
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ExternalIssueShape
 * @property {*} name
 * @property {*} url
 * @property {*} key
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(ColorCoding|object)} FieldBasedColorCoding
 */

/**
 * @typedef {(ColorCodingShape|object)} FieldBasedColorCodingShape
 */

/**
 * @typedef {object} FieldStyle
 * @property {string} background
 * @property {string} foreground
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} FieldStyleShape
 * @property {*} background
 * @property {*} foreground
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} FieldType
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} FieldTypeShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} FilterField
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} FilterFieldShape
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} GeneralUserProfile
 * @property {DateFormatDescriptor} dateFieldFormat
 * @property {TimeZoneDescriptor} timezone
 * @property {LocaleDescriptor} locale
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} GeneralUserProfileShape
 * @property {DateFormatDescriptorShape} dateFieldFormat
 * @property {TimeZoneDescriptorShape} timezone
 * @property {LocaleDescriptorShape} locale
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} GlobalSettings
 * @property {SystemSettings} systemSettings
 * @property {NotificationSettings} notificationSettings
 * @property {RestCorsSettings} restSettings
 * @property {AppearanceSettings} appearanceSettings
 * @property {LocaleSettings} localeSettings
 * @property {License} license
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} GlobalSettingsShape
 * @property {SystemSettingsShape} systemSettings
 * @property {NotificationSettingsShape} notificationSettings
 * @property {RestCorsSettingsShape} restSettings
 * @property {AppearanceSettingsShape} appearanceSettings
 * @property {LocaleSettingsShape} localeSettings
 * @property {LicenseShape} license
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} GlobalTimeTrackingSettings
 * @property {Array<WorkItemType>} workItemTypes
 * @property {WorkTimeSettings} workTimeSettings
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} GlobalTimeTrackingSettingsShape
 * @property {WorkItemTypeShape} workItemTypes
 * @property {WorkTimeSettingsShape} workTimeSettings
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(ProjectCustomField|object)} GroupProjectCustomField
 */

/**
 * @typedef {(ProjectCustomFieldShape|object)} GroupProjectCustomFieldShape
 */

/**
 * @typedef {object} Issue
 * @property {string} idReadable
 * @property {number} created
 * @property {number} updated
 * @property {number} resolved
 * @property {number} numberInProject
 * @property {Project} project
 * @property {string} summary
 * @property {string} description
 * @property {boolean} usesMarkdown
 * @property {string} wikifiedDescription
 * @property {User} reporter
 * @property {User} updater
 * @property {User} draftOwner
 * @property {boolean} isDraft
 * @property {Visibility} visibility
 * @property {number} votes
 * @property {Array<IssueComment>} comments
 * @property {number} commentsCount
 * @property {Array<IssueTag>} tags
 * @property {Array<IssueLink>} links
 * @property {ExternalIssue} externalIssue
 * @property {Array<IssueCustomField>} customFields
 * @property {IssueVoters} voters
 * @property {IssueWatchers} watchers
 * @property {Array<IssueAttachment>} attachments
 * @property {IssueLink} subtasks
 * @property {IssueLink} parent
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueShape
 * @property {*} idReadable
 * @property {*} created
 * @property {*} updated
 * @property {*} resolved
 * @property {*} numberInProject
 * @property {ProjectShape} project
 * @property {*} summary
 * @property {*} description
 * @property {*} usesMarkdown
 * @property {*} wikifiedDescription
 * @property {UserShape} reporter
 * @property {UserShape} updater
 * @property {UserShape} draftOwner
 * @property {*} isDraft
 * @property {VisibilityShape} visibility
 * @property {*} votes
 * @property {IssueCommentShape} comments
 * @property {*} commentsCount
 * @property {IssueTagShape} tags
 * @property {IssueLinkShape} links
 * @property {ExternalIssueShape} externalIssue
 * @property {IssueCustomFieldShape} customFields
 * @property {IssueVotersShape} voters
 * @property {IssueWatchersShape} watchers
 * @property {IssueAttachmentShape} attachments
 * @property {IssueLinkShape} subtasks
 * @property {IssueLinkShape} parent
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueAttachment
 * @property {string} name
 * @property {User} author
 * @property {number} created
 * @property {number} updated
 * @property {number} size
 * @property {string} extension
 * @property {string} charset
 * @property {string} mimeType
 * @property {string} metaData
 * @property {boolean} draft
 * @property {boolean} removed
 * @property {string} base64Content
 * @property {string} url
 * @property {Visibility} visibility
 * @property {Issue} issue
 * @property {IssueComment} comment
 * @property {string} thumbnailURL
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueAttachmentShape
 * @property {*} name
 * @property {UserShape} author
 * @property {*} created
 * @property {*} updated
 * @property {*} size
 * @property {*} extension
 * @property {*} charset
 * @property {*} mimeType
 * @property {*} metaData
 * @property {*} draft
 * @property {*} removed
 * @property {*} base64Content
 * @property {*} url
 * @property {VisibilityShape} visibility
 * @property {IssueShape} issue
 * @property {IssueCommentShape} comment
 * @property {*} thumbnailURL
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(SwimlaneSettings|object)} IssueBasedSwimlaneSettings
 */

/**
 * @typedef {(SwimlaneSettingsShape|object)} IssueBasedSwimlaneSettingsShape
 */

/**
 * @typedef {object} IssueComment
 * @property {string} text
 * @property {boolean} usesMarkdown
 * @property {string} textPreview
 * @property {number} created
 * @property {number} updated
 * @property {User} author
 * @property {Issue} issue
 * @property {Array<IssueAttachment>} attachments
 * @property {Visibility} visibility
 * @property {boolean} deleted
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueCommentShape
 * @property {*} text
 * @property {*} usesMarkdown
 * @property {*} textPreview
 * @property {*} created
 * @property {*} updated
 * @property {UserShape} author
 * @property {IssueShape} issue
 * @property {IssueAttachmentShape} attachments
 * @property {VisibilityShape} visibility
 * @property {*} deleted
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} IssueCreatedActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemShape|object)} IssueCreatedActivityItemShape
 */

/**
 * @typedef {object} IssueCustomField
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueCustomFieldShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueFolder
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueFolderShape
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueLink
 * @property {string} direction
 * @property {IssueLinkType} linkType
 * @property {Array<Issue>} issues
 * @property {Array<Issue>} trimmedIssues
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueLinkShape
 * @property {*} direction
 * @property {IssueLinkTypeShape} linkType
 * @property {IssueShape} issues
 * @property {IssueShape} trimmedIssues
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueLinkType
 * @property {string} name
 * @property {string} localizedName
 * @property {string} sourceToTarget
 * @property {string} localizedSourceToTarget
 * @property {string} targetToSource
 * @property {string} localizedTargetToSource
 * @property {boolean} directed
 * @property {boolean} aggregation
 * @property {boolean} readOnly
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueLinkTypeShape
 * @property {*} name
 * @property {*} localizedName
 * @property {*} sourceToTarget
 * @property {*} localizedSourceToTarget
 * @property {*} targetToSource
 * @property {*} localizedTargetToSource
 * @property {*} directed
 * @property {*} aggregation
 * @property {*} readOnly
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(SimpleValueActivityItem|object)} IssueResolvedActivityItem
 */

/**
 * @typedef {(SimpleValueActivityItemShape|object)} IssueResolvedActivityItemShape
 */

/**
 * @typedef {(WatchFolder|object)} IssueTag
 */

/**
 * @typedef {(WatchFolderShape|object)} IssueTagShape
 */

/**
 * @typedef {object} IssueTimeTracker
 * @property {Array<IssueWorkItem>} workItems
 * @property {boolean} enabled
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueTimeTrackerShape
 * @property {IssueWorkItemShape} workItems
 * @property {*} enabled
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueVoters
 * @property {boolean} hasVote
 * @property {Array<User>} original
 * @property {Array<DuplicateVote>} duplicate
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueVotersShape
 * @property {*} hasVote
 * @property {UserShape} original
 * @property {DuplicateVoteShape} duplicate
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueWatcher
 * @property {User} user
 * @property {Issue} issue
 * @property {boolean} isStarred
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueWatcherShape
 * @property {UserShape} user
 * @property {IssueShape} issue
 * @property {*} isStarred
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueWatchers
 * @property {boolean} hasStar
 * @property {Array<IssueWatcher>} issueWatchers
 * @property {Array<IssueWatcher>} duplicateWatchers
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueWatchersShape
 * @property {*} hasStar
 * @property {IssueWatcherShape} issueWatchers
 * @property {IssueWatcherShape} duplicateWatchers
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} IssueWorkItem
 * @property {User} author
 * @property {User} creator
 * @property {string} text
 * @property {string} textPreview
 * @property {WorkItemType} type
 * @property {number} created
 * @property {number} updated
 * @property {DurationValue} duration
 * @property {number} date
 * @property {Issue} issue
 * @property {boolean} usesMarkdown
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} IssueWorkItemShape
 * @property {UserShape} author
 * @property {UserShape} creator
 * @property {*} text
 * @property {*} textPreview
 * @property {WorkItemTypeShape} type
 * @property {*} created
 * @property {*} updated
 * @property {DurationValueShape} duration
 * @property {*} date
 * @property {IssueShape} issue
 * @property {*} usesMarkdown
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} JabberSettings
 * @property {boolean} isEnabled
 * @property {string} host
 * @property {number} port
 * @property {string} login
 * @property {string} serviceName
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} JabberSettingsShape
 * @property {*} isEnabled
 * @property {*} host
 * @property {*} port
 * @property {*} login
 * @property {*} serviceName
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} License
 * @property {string} username
 * @property {string} license
 * @property {string} error
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} LicenseShape
 * @property {*} username
 * @property {*} license
 * @property {*} error
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(Visibility|object)} LimitedVisibility
 */

/**
 * @typedef {(VisibilityShape|object)} LimitedVisibilityShape
 */

/**
 * @typedef {(MultiValueActivityItem|object)} LinksActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemShape|object)} LinksActivityItemShape
 */

/**
 * @typedef {object} LocaleDescriptor
 * @property {string} locale
 * @property {string} language
 * @property {boolean} community
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} LocaleDescriptorShape
 * @property {*} locale
 * @property {*} language
 * @property {*} community
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} LocaleSettings
 * @property {LocaleDescriptor} locale
 * @property {boolean} isRTL
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} LocaleSettingsShape
 * @property {LocaleDescriptorShape} locale
 * @property {*} isRTL
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BundleElement|object)} LocalizableBundleElement
 */

/**
 * @typedef {(BundleElementShape|object)} LocalizableBundleElementShape
 */

/**
 * @typedef {object} Logo
 * @property {string} url
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} LogoShape
 * @property {*} url
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(User)} Me
 */

/**
 * @typedef {(UserShape)} MeShape
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiBuildIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldShape|object)} MultiBuildIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiEnumIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldShape|object)} MultiEnumIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiGroupIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldShape|object)} MultiGroupIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiOwnedIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldShape|object)} MultiOwnedIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiUserIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldShape|object)} MultiUserIssueCustomFieldShape
 */

/**
 * @typedef {(ActivityItem)} MultiValueActivityItem
 */

/**
 * @typedef {(ActivityItemShape)} MultiValueActivityItemShape
 */

/**
 * @typedef {(IssueCustomField|object)} DatabaseMultiValueIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldShape|object)} DatabaseMultiValueIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomField|object)} MultiVersionIssueCustomField
 */

/**
 * @typedef {(DatabaseMultiValueIssueCustomFieldShape|object)} MultiVersionIssueCustomFieldShape
 */

/**
 * @typedef {object} NotificationSettings
 * @property {EmailSettings} emailSettings
 * @property {JabberSettings} jabberSettings
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} NotificationSettingsShape
 * @property {EmailSettingsShape} emailSettings
 * @property {JabberSettingsShape} jabberSettings
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} NotificationsUserProfile
 * @property {boolean} notifyOnOwnChanges
 * @property {boolean} jabberNotificationsEnabled
 * @property {boolean} emailNotificationsEnabled
 * @property {boolean} mentionNotificationsEnabled
 * @property {boolean} duplicateClusterNotificationsEnabled
 * @property {boolean} mailboxIntegrationNotificationsEnabled
 * @property {boolean} usePlainTextEmails
 * @property {boolean} autoWatchOnComment
 * @property {boolean} autoWatchOnVote
 * @property {boolean} autoWatchOnUpdate
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} NotificationsUserProfileShape
 * @property {*} notifyOnOwnChanges
 * @property {*} jabberNotificationsEnabled
 * @property {*} emailNotificationsEnabled
 * @property {*} mentionNotificationsEnabled
 * @property {*} duplicateClusterNotificationsEnabled
 * @property {*} mailboxIntegrationNotificationsEnabled
 * @property {*} usePlainTextEmails
 * @property {*} autoWatchOnComment
 * @property {*} autoWatchOnVote
 * @property {*} autoWatchOnUpdate
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} OnlineUsers
 * @property {number} users
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} OnlineUsersShape
 * @property {*} users
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BaseBundle|object)} OwnedBundle
 */

/**
 * @typedef {(BaseBundleShape|object)} OwnedBundleShape
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} OwnedBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsShape|object)} OwnedBundleCustomFieldDefaultsShape
 */

/**
 * @typedef {(BundleElement|object)} OwnedBundleElement
 */

/**
 * @typedef {(BundleElementShape|object)} OwnedBundleElementShape
 */

/**
 * @typedef {(BundleProjectCustomField|object)} OwnedProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldShape|object)} OwnedProjectCustomFieldShape
 */

/**
 * @typedef {object} ParsedCommand
 * @property {string} description
 * @property {boolean} error
 * @property {boolean} delete
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ParsedCommandShape
 * @property {*} description
 * @property {*} error
 * @property {*} delete
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} PeriodFieldFormat
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} PeriodFieldFormatShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(IssueCustomField|object)} PeriodIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldShape|object)} PeriodIssueCustomFieldShape
 */

/**
 * @typedef {(ProjectCustomField)} PeriodProjectCustomField
 */

/**
 * @typedef {(ProjectCustomFieldShape)} PeriodProjectCustomFieldShape
 */

/**
 * @typedef {object} PeriodValue
 * @property {number} minutes
 * @property {string} presentation
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} PeriodValueShape
 * @property {*} minutes
 * @property {*} presentation
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(FilterField)} PredefinedFilterField
 */

/**
 * @typedef {(FilterFieldShape)} PredefinedFilterFieldShape
 */

/**
 * @typedef {(IssueFolder|object)} Project
 */

/**
 * @typedef {(IssueFolderShape|object)} ProjectShape
 */

/**
 * @typedef {(SingleValueActivityItem|object)} ProjectActivityItem
 */

/**
 * @typedef {(SingleValueActivityItemShape|object)} ProjectActivityItemShape
 */

/**
 * @typedef {(ColorCoding|object)} ProjectBasedColorCoding
 */

/**
 * @typedef {(ColorCodingShape|object)} ProjectBasedColorCodingShape
 */

/**
 * @typedef {object} ProjectColor
 * @property {Project} project
 * @property {FieldStyle} color
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ProjectColorShape
 * @property {ProjectShape} project
 * @property {FieldStyleShape} color
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ProjectCustomField
 * @property {CustomField} field
 * @property {Project} project
 * @property {boolean} canBeEmpty
 * @property {string} emptyFieldText
 * @property {number} ordinal
 * @property {boolean} isPublic
 * @property {boolean} hasRunningJob
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ProjectCustomFieldShape
 * @property {CustomFieldShape} field
 * @property {ProjectShape} project
 * @property {*} canBeEmpty
 * @property {*} emptyFieldText
 * @property {*} ordinal
 * @property {*} isPublic
 * @property {*} hasRunningJob
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} ProjectTimeTrackingSettings
 * @property {boolean} enabled
 * @property {ProjectCustomField} estimate
 * @property {ProjectCustomField} timeSpent
 * @property {Array<WorkItemType>} workItemTypes
 * @property {Project} project
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} ProjectTimeTrackingSettingsShape
 * @property {*} enabled
 * @property {ProjectCustomFieldShape} estimate
 * @property {ProjectCustomFieldShape} timeSpent
 * @property {WorkItemTypeShape} workItemTypes
 * @property {ProjectShape} project
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} RestCorsSettings
 * @property {string} allowedOrigins
 * @property {boolean} allowAllOrigins
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} RestCorsSettingsShape
 * @property {*} allowedOrigins
 * @property {*} allowAllOrigins
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(WatchFolder|object)} SavedQuery
 */

/**
 * @typedef {(WatchFolderShape|object)} SavedQueryShape
 */

/**
 * @typedef {(IssueCustomField|object)} SimpleIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldShape|object)} SimpleIssueCustomFieldShape
 */

/**
 * @typedef {(ProjectCustomField)} SimpleProjectCustomField
 */

/**
 * @typedef {(ProjectCustomFieldShape)} SimpleProjectCustomFieldShape
 */

/**
 * @typedef {(SingleValueActivityItem|object)} SimpleValueActivityItem
 */

/**
 * @typedef {(SingleValueActivityItemShape|object)} SimpleValueActivityItemShape
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleBuildIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldShape|object)} SingleBuildIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleEnumIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldShape|object)} SingleEnumIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleGroupIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldShape|object)} SingleGroupIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleOwnedIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldShape|object)} SingleOwnedIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleUserIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldShape|object)} SingleUserIssueCustomFieldShape
 */

/**
 * @typedef {(ActivityItem)} SingleValueActivityItem
 */

/**
 * @typedef {(ActivityItemShape)} SingleValueActivityItemShape
 */

/**
 * @typedef {(IssueCustomField|object)} DatabaseSingleValueIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldShape|object)} DatabaseSingleValueIssueCustomFieldShape
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} SingleVersionIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldShape|object)} SingleVersionIssueCustomFieldShape
 */

/**
 * @typedef {object} Sprint
 * @property {Agile} agile
 * @property {string} name
 * @property {string} goal
 * @property {number} start
 * @property {number} finish
 * @property {boolean} archived
 * @property {boolean} isDefault
 * @property {Array<Issue>} issues
 * @property {number} unresolvedIssuesCount
 * @property {Sprint} previousSprint
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SprintShape
 * @property {AgileShape} agile
 * @property {*} name
 * @property {*} goal
 * @property {*} start
 * @property {*} finish
 * @property {*} archived
 * @property {*} isDefault
 * @property {IssueShape} issues
 * @property {*} unresolvedIssuesCount
 * @property {SprintShape} previousSprint
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(MultiValueActivityItem|object)} SprintActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemShape|object)} SprintActivityItemShape
 */

/**
 * @typedef {object} SprintsSettings
 * @property {boolean} isExplicit
 * @property {boolean} cardOnSeveralSprints
 * @property {Sprint} defaultSprint
 * @property {boolean} disableSprints
 * @property {string} explicitQuery
 * @property {CustomField} sprintSyncField
 * @property {boolean} hideSubtasksOfCards
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SprintsSettingsShape
 * @property {*} isExplicit
 * @property {*} cardOnSeveralSprints
 * @property {SprintShape} defaultSprint
 * @property {*} disableSprints
 * @property {*} explicitQuery
 * @property {CustomFieldShape} sprintSyncField
 * @property {*} hideSubtasksOfCards
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BaseBundle|object)} StateBundle
 */

/**
 * @typedef {(BaseBundleShape|object)} StateBundleShape
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} StateBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsShape|object)} StateBundleCustomFieldDefaultsShape
 */

/**
 * @typedef {(LocalizableBundleElement|object)} StateBundleElement
 */

/**
 * @typedef {(LocalizableBundleElementShape|object)} StateBundleElementShape
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomField|object)} StateIssueCustomField
 */

/**
 * @typedef {(DatabaseSingleValueIssueCustomFieldShape|object)} StateIssueCustomFieldShape
 */

/**
 * @typedef {(BundleProjectCustomField|object)} StateProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldShape|object)} StateProjectCustomFieldShape
 */

/**
 * @typedef {object} StorageEntry
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} StorageEntryShape
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} Suggestion
 * @property {number} completionStart
 * @property {number} completionEnd
 * @property {number} matchingStart
 * @property {number} matchingEnd
 * @property {number} caret
 * @property {string} description
 * @property {string} option
 * @property {string} prefix
 * @property {string} suffix
 * @property {string} group
 * @property {string} icon
 * @property {string} auxiliaryIcon
 * @property {string} className
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SuggestionShape
 * @property {*} completionStart
 * @property {*} completionEnd
 * @property {*} matchingStart
 * @property {*} matchingEnd
 * @property {*} caret
 * @property {*} description
 * @property {*} option
 * @property {*} prefix
 * @property {*} suffix
 * @property {*} group
 * @property {*} icon
 * @property {*} auxiliaryIcon
 * @property {*} className
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(DatabaseAttributeValue|object)} SwimlaneEntityAttributeValue
 */

/**
 * @typedef {(DatabaseAttributeValueShape|object)} SwimlaneEntityAttributeValueShape
 */

/**
 * @typedef {object} SwimlaneSettings
 * @property {boolean} enabled
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SwimlaneSettingsShape
 * @property {*} enabled
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} SwimlaneValue
 * @property {string} name
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SwimlaneValueShape
 * @property {*} name
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} SystemSettings
 * @property {string} baseUrl
 * @property {number} maxUploadFileSize
 * @property {number} maxExportItems
 * @property {string} administratorEmail
 * @property {boolean} allowStatisticsCollection
 * @property {boolean} isApplicationReadOnly
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} SystemSettingsShape
 * @property {*} baseUrl
 * @property {*} maxUploadFileSize
 * @property {*} maxExportItems
 * @property {*} administratorEmail
 * @property {*} allowStatisticsCollection
 * @property {*} isApplicationReadOnly
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(MultiValueActivityItem|object)} TagsActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemShape|object)} TagsActivityItemShape
 */

/**
 * @typedef {object} Telemetry
 * @property {string} installationFolder
 * @property {string} databaseLocation
 * @property {string} logsLocation
 * @property {number} availableProcessors
 * @property {string} availableMemory
 * @property {string} allocatedMemory
 * @property {string} usedMemory
 * @property {string} uptime
 * @property {number} startedTime
 * @property {number} databaseBackgroundThreads
 * @property {number} pendingAsyncJobs
 * @property {number} cachedResultsCountInDBQueriesCache
 * @property {string} databaseQueriesCacheHitRate
 * @property {string} blobStringsCacheHitRate
 * @property {number} totalTransactions
 * @property {string} transactionsPerSecond
 * @property {string} requestsPerSecond
 * @property {string} databaseSize
 * @property {string} fullDatabaseSize
 * @property {string} textIndexSize
 * @property {OnlineUsers} onlineUsers
 * @property {number} reportCalculatorThreads
 * @property {number} notificationAnalyzerThreads
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} TelemetryShape
 * @property {*} installationFolder
 * @property {*} databaseLocation
 * @property {*} logsLocation
 * @property {*} availableProcessors
 * @property {*} availableMemory
 * @property {*} allocatedMemory
 * @property {*} usedMemory
 * @property {*} uptime
 * @property {*} startedTime
 * @property {*} databaseBackgroundThreads
 * @property {*} pendingAsyncJobs
 * @property {*} cachedResultsCountInDBQueriesCache
 * @property {*} databaseQueriesCacheHitRate
 * @property {*} blobStringsCacheHitRate
 * @property {*} totalTransactions
 * @property {*} transactionsPerSecond
 * @property {*} requestsPerSecond
 * @property {*} databaseSize
 * @property {*} fullDatabaseSize
 * @property {*} textIndexSize
 * @property {OnlineUsersShape} onlineUsers
 * @property {*} reportCalculatorThreads
 * @property {*} notificationAnalyzerThreads
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(CustomFieldActivityItem|object)} TextCustomFieldActivityItem
 */

/**
 * @typedef {(CustomFieldActivityItemShape|object)} TextCustomFieldActivityItemShape
 */

/**
 * @typedef {object} TextFieldValue
 * @property {string} text
 * @property {string} markdownText
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} TextFieldValueShape
 * @property {*} text
 * @property {*} markdownText
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(IssueCustomField|object)} TextIssueCustomField
 */

/**
 * @typedef {(IssueCustomFieldShape|object)} TextIssueCustomFieldShape
 */

/**
 * @typedef {(SimpleValueActivityItem|object)} TextMarkupActivityItem
 */

/**
 * @typedef {(SimpleValueActivityItemShape|object)} TextMarkupActivityItemShape
 */

/**
 * @typedef {(SimpleProjectCustomField)} TextProjectCustomField
 */

/**
 * @typedef {(SimpleProjectCustomFieldShape)} TextProjectCustomFieldShape
 */

/**
 * @typedef {object} TimeTrackingUserProfile
 * @property {PeriodFieldFormat} periodFormat
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} TimeTrackingUserProfileShape
 * @property {PeriodFieldFormatShape} periodFormat
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {object} TimeZoneDescriptor
 * @property {string} presentation
 * @property {number} offset
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} TimeZoneDescriptorShape
 * @property {*} presentation
 * @property {*} offset
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(Visibility)} UnlimitedVisibility
 */

/**
 * @typedef {(VisibilityShape)} UnlimitedVisibilityShape
 */

/**
 * @typedef {object} User
 * @property {string} login
 * @property {string} fullName
 * @property {string} email
 * @property {string} jabberAccountName
 * @property {string} ringId
 * @property {boolean} guest
 * @property {boolean} online
 * @property {boolean} banned
 * @property {Array<IssueTag>} tags
 * @property {Array<SavedQuery>} savedQueries
 * @property {string} avatarUrl
 * @property {object} profiles
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} UserShape
 * @property {*} login
 * @property {*} fullName
 * @property {*} email
 * @property {*} jabberAccountName
 * @property {*} ringId
 * @property {*} guest
 * @property {*} online
 * @property {*} banned
 * @property {IssueTagShape} tags
 * @property {SavedQueryShape} savedQueries
 * @property {*} avatarUrl
 * @property {object} profiles
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(Bundle|object)} UserBundle
 */

/**
 * @typedef {(BundleShape|object)} UserBundleShape
 */

/**
 * @typedef {(CustomFieldDefaults|object)} UserCustomFieldDefaults
 */

/**
 * @typedef {(CustomFieldDefaultsShape|object)} UserCustomFieldDefaultsShape
 */

/**
 * @typedef {object} UserGroup
 * @property {string} name
 * @property {string} ringId
 * @property {number} usersCount
 * @property {string} icon
 * @property {boolean} allUsersGroup
 * @property {Project} teamForProject
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} UserGroupShape
 * @property {*} name
 * @property {*} ringId
 * @property {*} usersCount
 * @property {*} icon
 * @property {*} allUsersGroup
 * @property {ProjectShape} teamForProject
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(BundleProjectCustomField|object)} UserProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldShape|object)} UserProjectCustomFieldShape
 */

/**
 * @typedef {(SimpleValueActivityItem|object)} UsesMarkupActivityItem
 */

/**
 * @typedef {(SimpleValueActivityItemShape|object)} UsesMarkupActivityItemShape
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} VcsChangeActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemShape|object)} VcsChangeActivityItemShape
 */

/**
 * @typedef {(User|object)} VcsUnresolvedUser
 */

/**
 * @typedef {(UserShape|object)} VcsUnresolvedUserShape
 */

/**
 * @typedef {(BaseBundle|object)} VersionBundle
 */

/**
 * @typedef {(BaseBundleShape|object)} VersionBundleShape
 */

/**
 * @typedef {(BundleCustomFieldDefaults|object)} VersionBundleCustomFieldDefaults
 */

/**
 * @typedef {(BundleCustomFieldDefaultsShape|object)} VersionBundleCustomFieldDefaultsShape
 */

/**
 * @typedef {(BundleElement|object)} VersionBundleElement
 */

/**
 * @typedef {(BundleElementShape|object)} VersionBundleElementShape
 */

/**
 * @typedef {(BundleProjectCustomField|object)} VersionProjectCustomField
 */

/**
 * @typedef {(BundleProjectCustomFieldShape|object)} VersionProjectCustomFieldShape
 */

/**
 * @typedef {object} Visibility
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} VisibilityShape
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(MultiValueActivityItem|object)} VisibilityActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemShape|object)} VisibilityActivityItemShape
 */

/**
 * @typedef {(VisibilityActivityItem|object)} VisibilityGroupActivityItem
 */

/**
 * @typedef {(VisibilityActivityItemShape|object)} VisibilityGroupActivityItemShape
 */

/**
 * @typedef {(VisibilityActivityItem|object)} VisibilityUserActivityItem
 */

/**
 * @typedef {(VisibilityActivityItemShape|object)} VisibilityUserActivityItemShape
 */

/**
 * @typedef {(MultiValueActivityItem|object)} VotersActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemShape|object)} VotersActivityItemShape
 */

/**
 * @typedef {object} WIPLimit
 * @property {number} max
 * @property {number} min
 * @property {AgileColumn} column
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} WIPLimitShape
 * @property {*} max
 * @property {*} min
 * @property {AgileColumnShape} column
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(IssueFolder|object)} WatchFolder
 */

/**
 * @typedef {(IssueFolderShape|object)} WatchFolderShape
 */

/**
 * @typedef {(CreatedDeletedActivityItem|object)} WorkItemActivityItem
 */

/**
 * @typedef {(CreatedDeletedActivityItemShape|object)} WorkItemActivityItemShape
 */

/**
 * @typedef {(SingleValueActivityItem|object)} WorkItemAuthorActivityItem
 */

/**
 * @typedef {(SingleValueActivityItemShape|object)} WorkItemAuthorActivityItemShape
 */

/**
 * @typedef {(SingleValueActivityItem|object)} WorkItemDurationActivityItem
 */

/**
 * @typedef {(SingleValueActivityItemShape|object)} WorkItemDurationActivityItemShape
 */

/**
 * @typedef {object} WorkItemType
 * @property {string} name
 * @property {boolean} autoAttached
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} WorkItemTypeShape
 * @property {*} name
 * @property {*} autoAttached
 * @property {*} id
 * @property {*} $type
 */

/**
 * @typedef {(MultiValueActivityItem|object)} WorkItemTypeActivityItem
 */

/**
 * @typedef {(MultiValueActivityItemShape|object)} WorkItemTypeActivityItemShape
 */

/**
 * @typedef {object} WorkTimeSettings
 * @property {number} minutesADay
 * @property {number} workDays
 * @property {number} firstDayOfWeek
 * @property {number} daysAWeek
 * @property {string} id
 * @property {string} $type
 */

/**
 * @typedef {object} WorkTimeSettingsShape
 * @property {*} minutesADay
 * @property {*} workDays
 * @property {*} firstDayOfWeek
 * @property {*} daysAWeek
 * @property {*} id
 * @property {*} $type
 */