// AUTOGENERATED FILE DO NOT EDIT!
// This file was generated by script

/**
 * @template T
 * @typedef YoRequest
 * @property {string} method
 * @property {string} path
 * @property {any} [query]
 */

/**
 * @param {string} path
 * @param {object} [params]
 * @returns {string}
 */
export function interpolate(path, params) {
  return (params ?
    path.replace(/{([^{}]+)}/g,
      (_, paramName) => params.hasOwnProperty(paramName) ? params[paramName] : _
    ) :
    path);
}

/**
 * @typedef {object} GetActivitiesRequestOptions
 * @property {object} [query]
 * @property {string} [query.categories]
 * @property {boolean} [query.reverse]
 * @property {string} [query.start]
 * @property {string} [query.end]
 * @property {string} [query.author]
 * @property {string} [query.issueQuery]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetActivitiesRequestOptions} options
 * @returns {YoRequest<Array<ActivityItem>>}
 */
export function createGetActivitiesRequest(options) {
  return {method: 'get', path: '/api/activities', query: options.query};
}

/**
 * @typedef {object} GetActivitiesActivityItemRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetActivitiesActivityItemRequestOptions} options
 * @returns {YoRequest<ActivityItem>}
 */
export function createGetActivitiesActivityItemRequest(options) {
  return {method: 'get', path: interpolate('/api/activities/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} GetActivitiesPageRequestOptions
 * @property {object} [query]
 * @property {string} [query.categories]
 * @property {boolean} [query.reverse]
 * @property {string} [query.start]
 * @property {string} [query.end]
 * @property {string} [query.author]
 * @property {string} [query.issueQuery]
 * @property {string} [query.cursor]
 * @property {string} [query.activityId]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetActivitiesPageRequestOptions} options
 * @returns {YoRequest<ActivityCursorPage>}
 */
export function createGetActivitiesPageRequest(options) {
  return {method: 'get', path: interpolate('/api/activitiesPage', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesBuildRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesBuildRequestOptions} options
 * @returns {YoRequest<Array<BuildBundle>>}
 */
export function createGetAdminCustomFieldSettingsBundlesBuildRequest(options) {
  return {method: 'get', path: '/api/admin/customFieldSettings/bundles/build', query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesBuildRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesBuildRequestOptions} options
 * @returns {YoRequest<BuildBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesBuildRequest(options) {
  return {method: 'post', path: '/api/admin/customFieldSettings/bundles/build', query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions} options
 * @returns {YoRequest<BuildBundle>}
 */
export function createGetAdminCustomFieldSettingsBundlesBuildBuildBundleRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/build/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions} options
 * @returns {YoRequest<BuildBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesBuildBuildBundleRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/bundles/build/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsBundlesBuildBuildBundleRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/bundles/build/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesEnumRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesEnumRequestOptions} options
 * @returns {YoRequest<Array<EnumBundle>>}
 */
export function createGetAdminCustomFieldSettingsBundlesEnumRequest(options) {
  return {method: 'get', path: '/api/admin/customFieldSettings/bundles/enum', query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesEnumRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesEnumRequestOptions} options
 * @returns {YoRequest<EnumBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesEnumRequest(options) {
  return {method: 'post', path: '/api/admin/customFieldSettings/bundles/enum', query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions} options
 * @returns {YoRequest<EnumBundle>}
 */
export function createGetAdminCustomFieldSettingsBundlesEnumEnumBundleRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/enum/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions} options
 * @returns {YoRequest<EnumBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesEnumEnumBundleRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/bundles/enum/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsBundlesEnumEnumBundleRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/bundles/enum/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesOwnedFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesOwnedFieldRequestOptions} options
 * @returns {YoRequest<Array<OwnedBundle>>}
 */
export function createGetAdminCustomFieldSettingsBundlesOwnedFieldRequest(options) {
  return {method: 'get', path: '/api/admin/customFieldSettings/bundles/ownedField', query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesOwnedFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesOwnedFieldRequestOptions} options
 * @returns {YoRequest<OwnedBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesOwnedFieldRequest(options) {
  return {method: 'post', path: '/api/admin/customFieldSettings/bundles/ownedField', query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions} options
 * @returns {YoRequest<OwnedBundle>}
 */
export function createGetAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/ownedField/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions} options
 * @returns {YoRequest<OwnedBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/bundles/ownedField/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/bundles/ownedField/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesStateRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesStateRequestOptions} options
 * @returns {YoRequest<Array<StateBundle>>}
 */
export function createGetAdminCustomFieldSettingsBundlesStateRequest(options) {
  return {method: 'get', path: '/api/admin/customFieldSettings/bundles/state', query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesStateRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesStateRequestOptions} options
 * @returns {YoRequest<StateBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesStateRequest(options) {
  return {method: 'post', path: '/api/admin/customFieldSettings/bundles/state', query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions} options
 * @returns {YoRequest<StateBundle>}
 */
export function createGetAdminCustomFieldSettingsBundlesStateStateBundleRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/state/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions} options
 * @returns {YoRequest<StateBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesStateStateBundleRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/bundles/state/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsBundlesStateStateBundleRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/bundles/state/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesUserRequestOptions} options
 * @returns {YoRequest<Array<UserBundle>>}
 */
export function createGetAdminCustomFieldSettingsBundlesUserRequest(options) {
  return {method: 'get', path: '/api/admin/customFieldSettings/bundles/user', query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesUserRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesUserRequestOptions} options
 * @returns {YoRequest<UserBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesUserRequest(options) {
  return {method: 'post', path: '/api/admin/customFieldSettings/bundles/user', query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions} options
 * @returns {YoRequest<UserBundle>}
 */
export function createGetAdminCustomFieldSettingsBundlesUserUserBundleRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions} options
 * @returns {YoRequest<UserBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesUserUserBundleRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsBundlesUserUserBundleRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserAggregatedUsersRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesUserAggregatedUsersRequestOptions} options
 * @returns {YoRequest<Array<User>>}
 */
export function createGetAdminCustomFieldSettingsBundlesUserAggregatedUsersRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/aggregatedUsers', options.path), query: options.query};
}



/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserGroupsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesUserGroupsRequestOptions} options
 * @returns {YoRequest<Array<UserGroup>>}
 */
export function createGetAdminCustomFieldSettingsBundlesUserGroupsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/groups', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesUserGroupsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesUserGroupsRequestOptions} options
 * @returns {YoRequest<UserGroup>}
 */
export function createPostAdminCustomFieldSettingsBundlesUserGroupsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/groups', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserGroupsUserGroupRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.userGroupId
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesUserGroupsUserGroupRequestOptions} options
 * @returns {YoRequest<UserGroup>}
 */
export function createGetAdminCustomFieldSettingsBundlesUserGroupsUserGroupRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/groups/{userGroupId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesUserGroupsUserGroupRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.userGroupId
 */

/**
 * @param {DeleteAdminCustomFieldSettingsBundlesUserGroupsUserGroupRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsBundlesUserGroupsUserGroupRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/groups/{userGroupId}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserIndividualsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesUserIndividualsRequestOptions} options
 * @returns {YoRequest<Array<User>>}
 */
export function createGetAdminCustomFieldSettingsBundlesUserIndividualsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/individuals', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesUserIndividualsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesUserIndividualsRequestOptions} options
 * @returns {YoRequest<User>}
 */
export function createPostAdminCustomFieldSettingsBundlesUserIndividualsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/individuals', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserIndividualsUserRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.userId
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesUserIndividualsUserRequestOptions} options
 * @returns {YoRequest<User>}
 */
export function createGetAdminCustomFieldSettingsBundlesUserIndividualsUserRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/individuals/{userId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesUserIndividualsUserRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.userId
 */

/**
 * @param {DeleteAdminCustomFieldSettingsBundlesUserIndividualsUserRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsBundlesUserIndividualsUserRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/bundles/user/{id}/individuals/{userId}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesVersionRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesVersionRequestOptions} options
 * @returns {YoRequest<Array<VersionBundle>>}
 */
export function createGetAdminCustomFieldSettingsBundlesVersionRequest(options) {
  return {method: 'get', path: '/api/admin/customFieldSettings/bundles/version', query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesVersionRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesVersionRequestOptions} options
 * @returns {YoRequest<VersionBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesVersionRequest(options) {
  return {method: 'post', path: '/api/admin/customFieldSettings/bundles/version', query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions} options
 * @returns {YoRequest<VersionBundle>}
 */
export function createGetAdminCustomFieldSettingsBundlesVersionVersionBundleRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/bundles/version/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions} options
 * @returns {YoRequest<VersionBundle>}
 */
export function createPostAdminCustomFieldSettingsBundlesVersionVersionBundleRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/bundles/version/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsBundlesVersionVersionBundleRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/bundles/version/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsCustomFieldsRequestOptions} options
 * @returns {YoRequest<Array<CustomField>>}
 */
export function createGetAdminCustomFieldSettingsCustomFieldsRequest(options) {
  return {method: 'get', path: '/api/admin/customFieldSettings/customFields', query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAdminCustomFieldSettingsCustomFieldsRequestOptions} options
 * @returns {YoRequest<CustomField>}
 */
export function createPostAdminCustomFieldSettingsCustomFieldsRequest(options) {
  return {method: 'post', path: '/api/admin/customFieldSettings/customFields', query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions} options
 * @returns {YoRequest<CustomField>}
 */
export function createGetAdminCustomFieldSettingsCustomFieldsCustomFieldRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/customFields/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions} options
 * @returns {YoRequest<CustomField>}
 */
export function createPostAdminCustomFieldSettingsCustomFieldsCustomFieldRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/customFields/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminCustomFieldSettingsCustomFieldsCustomFieldRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/customFieldSettings/customFields/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsCustomFieldsFieldDefaultsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.customFieldDefaultsId
 */

/**
 * @param {GetAdminCustomFieldSettingsCustomFieldsFieldDefaultsRequestOptions} options
 * @returns {YoRequest<CustomFieldDefaults>}
 */
export function createGetAdminCustomFieldSettingsCustomFieldsFieldDefaultsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/customFields/{id}/fieldDefaults', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminCustomFieldSettingsCustomFieldsFieldDefaultsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.customFieldDefaultsId
 */

/**
 * @param {PostAdminCustomFieldSettingsCustomFieldsFieldDefaultsRequestOptions} options
 * @returns {YoRequest<CustomFieldDefaults>}
 */
export function createPostAdminCustomFieldSettingsCustomFieldsFieldDefaultsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/customFieldSettings/customFields/{id}/fieldDefaults', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminCustomFieldSettingsCustomFieldsInstancesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsCustomFieldsInstancesRequestOptions} options
 * @returns {YoRequest<Array<ProjectCustomField>>}
 */
export function createGetAdminCustomFieldSettingsCustomFieldsInstancesRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/customFieldSettings/customFields/{id}/instances', options.path), query: options.query};
}



/**
 * @typedef {object} GetAdminCustomFieldSettingsTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminCustomFieldSettingsTypesRequestOptions} options
 * @returns {YoRequest<Array<FieldType>>}
 */
export function createGetAdminCustomFieldSettingsTypesRequest(options) {
  return {method: 'get', path: '/api/admin/customFieldSettings/types', query: options.query};
}



/**
 * @typedef {object} GetAdminDatabaseBackupBackupsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminDatabaseBackupBackupsRequestOptions} options
 * @returns {YoRequest<Array<BackupFile>>}
 */
export function createGetAdminDatabaseBackupBackupsRequest(options) {
  return {method: 'get', path: '/api/admin/databaseBackup/backups', query: options.query};
}

/**
 * @typedef {object} GetAdminDatabaseBackupBackupsBackupFileRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminDatabaseBackupBackupsBackupFileRequestOptions} options
 * @returns {YoRequest<BackupFile>}
 */
export function createGetAdminDatabaseBackupBackupsBackupFileRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/databaseBackup/backups/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminDatabaseBackupSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminDatabaseBackupSettingsRequestOptions} options
 * @returns {YoRequest<DatabaseBackupSettings>}
 */
export function createGetAdminDatabaseBackupSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/databaseBackup/settings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminDatabaseBackupSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminDatabaseBackupSettingsRequestOptions} options
 * @returns {YoRequest<DatabaseBackupSettings>}
 */
export function createPostAdminDatabaseBackupSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/databaseBackup/settings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminDatabaseBackupSettingsBackupStatusRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.backupStatusId
 */

/**
 * @param {GetAdminDatabaseBackupSettingsBackupStatusRequestOptions} options
 * @returns {YoRequest<BackupStatus>}
 */
export function createGetAdminDatabaseBackupSettingsBackupStatusRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/databaseBackup/settings/backupStatus', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminGlobalSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminGlobalSettingsRequestOptions} options
 * @returns {YoRequest<GlobalSettings>}
 */
export function createGetAdminGlobalSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/globalSettings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminGlobalSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminGlobalSettingsRequestOptions} options
 * @returns {YoRequest<GlobalSettings>}
 */
export function createPostAdminGlobalSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/globalSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminGlobalSettingsAppearanceSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.appearanceSettingsId
 */

/**
 * @param {GetAdminGlobalSettingsAppearanceSettingsRequestOptions} options
 * @returns {YoRequest<AppearanceSettings>}
 */
export function createGetAdminGlobalSettingsAppearanceSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/globalSettings/appearanceSettings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminGlobalSettingsAppearanceSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.appearanceSettingsId
 */

/**
 * @param {PostAdminGlobalSettingsAppearanceSettingsRequestOptions} options
 * @returns {YoRequest<AppearanceSettings>}
 */
export function createPostAdminGlobalSettingsAppearanceSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/globalSettings/appearanceSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminGlobalSettingsLicenseRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.licenseId
 */

/**
 * @param {GetAdminGlobalSettingsLicenseRequestOptions} options
 * @returns {YoRequest<License>}
 */
export function createGetAdminGlobalSettingsLicenseRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/globalSettings/license', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminGlobalSettingsLicenseRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.licenseId
 */

/**
 * @param {PostAdminGlobalSettingsLicenseRequestOptions} options
 * @returns {YoRequest<License>}
 */
export function createPostAdminGlobalSettingsLicenseRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/globalSettings/license', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminGlobalSettingsLocaleSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.localeSettingsId
 */

/**
 * @param {GetAdminGlobalSettingsLocaleSettingsRequestOptions} options
 * @returns {YoRequest<LocaleSettings>}
 */
export function createGetAdminGlobalSettingsLocaleSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/globalSettings/localeSettings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminGlobalSettingsLocaleSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.localeSettingsId
 */

/**
 * @param {PostAdminGlobalSettingsLocaleSettingsRequestOptions} options
 * @returns {YoRequest<LocaleSettings>}
 */
export function createPostAdminGlobalSettingsLocaleSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/globalSettings/localeSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminGlobalSettingsNotificationSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.notificationSettingsId
 */

/**
 * @param {GetAdminGlobalSettingsNotificationSettingsRequestOptions} options
 * @returns {YoRequest<NotificationSettings>}
 */
export function createGetAdminGlobalSettingsNotificationSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/globalSettings/notificationSettings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminGlobalSettingsNotificationSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.notificationSettingsId
 */

/**
 * @param {PostAdminGlobalSettingsNotificationSettingsRequestOptions} options
 * @returns {YoRequest<NotificationSettings>}
 */
export function createPostAdminGlobalSettingsNotificationSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/globalSettings/notificationSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminGlobalSettingsRestSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.restCorsSettingsId
 */

/**
 * @param {GetAdminGlobalSettingsRestSettingsRequestOptions} options
 * @returns {YoRequest<RestCorsSettings>}
 */
export function createGetAdminGlobalSettingsRestSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/globalSettings/restSettings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminGlobalSettingsRestSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.restCorsSettingsId
 */

/**
 * @param {PostAdminGlobalSettingsRestSettingsRequestOptions} options
 * @returns {YoRequest<RestCorsSettings>}
 */
export function createPostAdminGlobalSettingsRestSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/globalSettings/restSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminGlobalSettingsSystemSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.systemSettingsId
 */

/**
 * @param {GetAdminGlobalSettingsSystemSettingsRequestOptions} options
 * @returns {YoRequest<SystemSettings>}
 */
export function createGetAdminGlobalSettingsSystemSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/globalSettings/systemSettings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminGlobalSettingsSystemSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.systemSettingsId
 */

/**
 * @param {PostAdminGlobalSettingsSystemSettingsRequestOptions} options
 * @returns {YoRequest<SystemSettings>}
 */
export function createPostAdminGlobalSettingsSystemSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/globalSettings/systemSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminProjectsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminProjectsRequestOptions} options
 * @returns {YoRequest<Array<Project>>}
 */
export function createGetAdminProjectsRequest(options) {
  return {method: 'get', path: '/api/admin/projects', query: options.query};
}

/**
 * @typedef {object} PostAdminProjectsRequestOptions
 * @property {object} [query]
 * @property {string} [query.template]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAdminProjectsRequestOptions} options
 * @returns {YoRequest<Project>}
 */
export function createPostAdminProjectsRequest(options) {
  return {method: 'post', path: '/api/admin/projects', query: options.query};
}

/**
 * @typedef {object} GetAdminProjectsProjectRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminProjectsProjectRequestOptions} options
 * @returns {YoRequest<Project>}
 */
export function createGetAdminProjectsProjectRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/projects/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminProjectsProjectRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminProjectsProjectRequestOptions} options
 * @returns {YoRequest<Project>}
 */
export function createPostAdminProjectsProjectRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/projects/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminProjectsProjectRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAdminProjectsProjectRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminProjectsProjectRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/projects/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminProjectsCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectCustomFieldId
 */

/**
 * @param {GetAdminProjectsCustomFieldsRequestOptions} options
 * @returns {YoRequest<ProjectCustomField>}
 */
export function createGetAdminProjectsCustomFieldsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/projects/{id}/customFields', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminProjectsCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectCustomFieldId
 */

/**
 * @param {PostAdminProjectsCustomFieldsRequestOptions} options
 * @returns {YoRequest<ProjectCustomField>}
 */
export function createPostAdminProjectsCustomFieldsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/projects/{id}/customFields', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminProjectsCustomFieldsRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectCustomFieldId
 */

/**
 * @param {DeleteAdminProjectsCustomFieldsRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminProjectsCustomFieldsRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/projects/{id}/customFields', options.path), query: null};
}

/**
 * @typedef {object} GetAdminProjectsIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminProjectsIssuesRequestOptions} options
 * @returns {YoRequest<Array<Issue>>}
 */
export function createGetAdminProjectsIssuesRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/projects/{id}/issues', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminProjectsIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminProjectsIssuesRequestOptions} options
 * @returns {YoRequest<Issue>}
 */
export function createPostAdminProjectsIssuesRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/projects/{id}/issues', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminProjectsIssuesIssueRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueId
 */

/**
 * @param {GetAdminProjectsIssuesIssueRequestOptions} options
 * @returns {YoRequest<Issue>}
 */
export function createGetAdminProjectsIssuesIssueRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/projects/{id}/issues/{issueId}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminProjectsIssuesIssueRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueId
 */

/**
 * @param {PostAdminProjectsIssuesIssueRequestOptions} options
 * @returns {YoRequest<Issue>}
 */
export function createPostAdminProjectsIssuesIssueRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/projects/{id}/issues/{issueId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminProjectsIssuesIssueRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueId
 */

/**
 * @param {DeleteAdminProjectsIssuesIssueRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminProjectsIssuesIssueRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/projects/{id}/issues/{issueId}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminProjectsTimeTrackingSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 */

/**
 * @param {GetAdminProjectsTimeTrackingSettingsRequestOptions} options
 * @returns {YoRequest<ProjectTimeTrackingSettings>}
 */
export function createGetAdminProjectsTimeTrackingSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/projects/{id}/timeTrackingSettings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminProjectsTimeTrackingSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 */

/**
 * @param {PostAdminProjectsTimeTrackingSettingsRequestOptions} options
 * @returns {YoRequest<ProjectTimeTrackingSettings>}
 */
export function createPostAdminProjectsTimeTrackingSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/projects/{id}/timeTrackingSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminProjectsTimeTrackingSettingsWorkItemTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminProjectsTimeTrackingSettingsWorkItemTypesRequestOptions} options
 * @returns {YoRequest<Array<WorkItemType>>}
 */
export function createGetAdminProjectsTimeTrackingSettingsWorkItemTypesRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/projects/{id}/timeTrackingSettings/workItemTypes', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminProjectsTimeTrackingSettingsWorkItemTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 */

/**
 * @param {PostAdminProjectsTimeTrackingSettingsWorkItemTypesRequestOptions} options
 * @returns {YoRequest<WorkItemType>}
 */
export function createPostAdminProjectsTimeTrackingSettingsWorkItemTypesRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/projects/{id}/timeTrackingSettings/workItemTypes', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminProjectsTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 * @property {string} path.workItemTypeId
 */

/**
 * @param {GetAdminProjectsTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions} options
 * @returns {YoRequest<WorkItemType>}
 */
export function createGetAdminProjectsTimeTrackingSettingsWorkItemTypesWorkItemTypeRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/projects/{id}/timeTrackingSettings/workItemTypes/{workItemTypeId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminProjectsTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 * @property {string} path.workItemTypeId
 */

/**
 * @param {DeleteAdminProjectsTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminProjectsTimeTrackingSettingsWorkItemTypesWorkItemTypeRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/projects/{id}/timeTrackingSettings/workItemTypes/{workItemTypeId}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminTimeTrackingSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAdminTimeTrackingSettingsRequestOptions} options
 * @returns {YoRequest<GlobalTimeTrackingSettings>}
 */
export function createGetAdminTimeTrackingSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/timeTrackingSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminTimeTrackingSettingsWorkItemTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAdminTimeTrackingSettingsWorkItemTypesRequestOptions} options
 * @returns {YoRequest<Array<WorkItemType>>}
 */
export function createGetAdminTimeTrackingSettingsWorkItemTypesRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/timeTrackingSettings/workItemTypes', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminTimeTrackingSettingsWorkItemTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAdminTimeTrackingSettingsWorkItemTypesRequestOptions} options
 * @returns {YoRequest<WorkItemType>}
 */
export function createPostAdminTimeTrackingSettingsWorkItemTypesRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/timeTrackingSettings/workItemTypes', options.path), query: options.query};
}

/**
 * @typedef {object} GetAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workItemTypeId
 */

/**
 * @param {GetAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions} options
 * @returns {YoRequest<WorkItemType>}
 */
export function createGetAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/timeTrackingSettings/workItemTypes/{workItemTypeId}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workItemTypeId
 */

/**
 * @param {PostAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions} options
 * @returns {YoRequest<WorkItemType>}
 */
export function createPostAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/timeTrackingSettings/workItemTypes/{workItemTypeId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workItemTypeId
 */

/**
 * @param {DeleteAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequest(options) {
  return {method: 'delete', path: interpolate('/api/admin/timeTrackingSettings/workItemTypes/{workItemTypeId}', options.path), query: null};
}

/**
 * @typedef {object} GetAdminTimeTrackingSettingsWorkTimeSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workTimeSettingsId
 */

/**
 * @param {GetAdminTimeTrackingSettingsWorkTimeSettingsRequestOptions} options
 * @returns {YoRequest<WorkTimeSettings>}
 */
export function createGetAdminTimeTrackingSettingsWorkTimeSettingsRequest(options) {
  return {method: 'get', path: interpolate('/api/admin/timeTrackingSettings/workTimeSettings', options.path), query: options.query};
}

/**
 * @typedef {object} PostAdminTimeTrackingSettingsWorkTimeSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workTimeSettingsId
 */

/**
 * @param {PostAdminTimeTrackingSettingsWorkTimeSettingsRequestOptions} options
 * @returns {YoRequest<WorkTimeSettings>}
 */
export function createPostAdminTimeTrackingSettingsWorkTimeSettingsRequest(options) {
  return {method: 'post', path: interpolate('/api/admin/timeTrackingSettings/workTimeSettings', options.path), query: options.query};
}

/**
 * @typedef {object} GetAgilesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAgilesRequestOptions} options
 * @returns {YoRequest<Array<Agile>>}
 */
export function createGetAgilesRequest(options) {
  return {method: 'get', path: '/api/agiles', query: options.query};
}

/**
 * @typedef {object} PostAgilesRequestOptions
 * @property {object} [query]
 * @property {string} [query.template]
 * @property {string} [query.fields]
 */

/**
 * @param {PostAgilesRequestOptions} options
 * @returns {YoRequest<Agile>}
 */
export function createPostAgilesRequest(options) {
  return {method: 'post', path: '/api/agiles', query: options.query};
}

/**
 * @typedef {object} GetAgilesAgileRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetAgilesAgileRequestOptions} options
 * @returns {YoRequest<Agile>}
 */
export function createGetAgilesAgileRequest(options) {
  return {method: 'get', path: interpolate('/api/agiles/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAgilesAgileRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAgilesAgileRequestOptions} options
 * @returns {YoRequest<Agile>}
 */
export function createPostAgilesAgileRequest(options) {
  return {method: 'post', path: interpolate('/api/agiles/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAgilesAgileRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteAgilesAgileRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAgilesAgileRequest(options) {
  return {method: 'delete', path: interpolate('/api/agiles/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetAgilesSprintsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetAgilesSprintsRequestOptions} options
 * @returns {YoRequest<Array<Sprint>>}
 */
export function createGetAgilesSprintsRequest(options) {
  return {method: 'get', path: interpolate('/api/agiles/{id}/sprints', options.path), query: options.query};
}

/**
 * @typedef {object} PostAgilesSprintsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostAgilesSprintsRequestOptions} options
 * @returns {YoRequest<Sprint>}
 */
export function createPostAgilesSprintsRequest(options) {
  return {method: 'post', path: interpolate('/api/agiles/{id}/sprints', options.path), query: options.query};
}

/**
 * @typedef {object} GetAgilesSprintsSprintRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.sprintId
 */

/**
 * @param {GetAgilesSprintsSprintRequestOptions} options
 * @returns {YoRequest<Sprint>}
 */
export function createGetAgilesSprintsSprintRequest(options) {
  return {method: 'get', path: interpolate('/api/agiles/{id}/sprints/{sprintId}', options.path), query: options.query};
}

/**
 * @typedef {object} PostAgilesSprintsSprintRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.sprintId
 */

/**
 * @param {PostAgilesSprintsSprintRequestOptions} options
 * @returns {YoRequest<Sprint>}
 */
export function createPostAgilesSprintsSprintRequest(options) {
  return {method: 'post', path: interpolate('/api/agiles/{id}/sprints/{sprintId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteAgilesSprintsSprintRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.sprintId
 */

/**
 * @param {DeleteAgilesSprintsSprintRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteAgilesSprintsSprintRequest(options) {
  return {method: 'delete', path: interpolate('/api/agiles/{id}/sprints/{sprintId}', options.path), query: null};
}





/**
 * @typedef {object} GetGroupsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetGroupsRequestOptions} options
 * @returns {YoRequest<Array<UserGroup>>}
 */
export function createGetGroupsRequest(options) {
  return {method: 'get', path: '/api/groups', query: options.query};
}

/**
 * @typedef {object} GetGroupsUserGroupRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetGroupsUserGroupRequestOptions} options
 * @returns {YoRequest<UserGroup>}
 */
export function createGetGroupsUserGroupRequest(options) {
  return {method: 'get', path: interpolate('/api/groups/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssueLinkTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssueLinkTypesRequestOptions} options
 * @returns {YoRequest<Array<IssueLinkType>>}
 */
export function createGetIssueLinkTypesRequest(options) {
  return {method: 'get', path: '/api/issueLinkTypes', query: options.query};
}

/**
 * @typedef {object} PostIssueLinkTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostIssueLinkTypesRequestOptions} options
 * @returns {YoRequest<IssueLinkType>}
 */
export function createPostIssueLinkTypesRequest(options) {
  return {method: 'post', path: '/api/issueLinkTypes', query: options.query};
}

/**
 * @typedef {object} GetIssueLinkTypesIssueLinkTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetIssueLinkTypesIssueLinkTypeRequestOptions} options
 * @returns {YoRequest<IssueLinkType>}
 */
export function createGetIssueLinkTypesIssueLinkTypeRequest(options) {
  return {method: 'get', path: interpolate('/api/issueLinkTypes/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssueLinkTypesIssueLinkTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostIssueLinkTypesIssueLinkTypeRequestOptions} options
 * @returns {YoRequest<IssueLinkType>}
 */
export function createPostIssueLinkTypesIssueLinkTypeRequest(options) {
  return {method: 'post', path: interpolate('/api/issueLinkTypes/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteIssueLinkTypesIssueLinkTypeRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteIssueLinkTypesIssueLinkTypeRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteIssueLinkTypesIssueLinkTypeRequest(options) {
  return {method: 'delete', path: interpolate('/api/issueLinkTypes/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetIssueTagsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssueTagsRequestOptions} options
 * @returns {YoRequest<Array<IssueTag>>}
 */
export function createGetIssueTagsRequest(options) {
  return {method: 'get', path: '/api/issueTags', query: options.query};
}

/**
 * @typedef {object} PostIssueTagsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostIssueTagsRequestOptions} options
 * @returns {YoRequest<IssueTag>}
 */
export function createPostIssueTagsRequest(options) {
  return {method: 'post', path: '/api/issueTags', query: options.query};
}

/**
 * @typedef {object} GetIssueTagsIssueTagRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetIssueTagsIssueTagRequestOptions} options
 * @returns {YoRequest<IssueTag>}
 */
export function createGetIssueTagsIssueTagRequest(options) {
  return {method: 'get', path: interpolate('/api/issueTags/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssueTagsIssueTagRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostIssueTagsIssueTagRequestOptions} options
 * @returns {YoRequest<IssueTag>}
 */
export function createPostIssueTagsIssueTagRequest(options) {
  return {method: 'post', path: interpolate('/api/issueTags/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteIssueTagsIssueTagRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteIssueTagsIssueTagRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteIssueTagsIssueTagRequest(options) {
  return {method: 'delete', path: interpolate('/api/issueTags/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetIssueTagsIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssueTagsIssuesRequestOptions} options
 * @returns {YoRequest<Array<Issue>>}
 */
export function createGetIssueTagsIssuesRequest(options) {
  return {method: 'get', path: interpolate('/api/issueTags/{id}/issues', options.path), query: options.query};
}



/**
 * @typedef {object} GetIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssuesRequestOptions} options
 * @returns {YoRequest<Array<Issue>>}
 */
export function createGetIssuesRequest(options) {
  return {method: 'get', path: '/api/issues', query: options.query};
}

/**
 * @typedef {object} PostIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.draftId]
 * @property {string} [query.fields]
 */

/**
 * @param {PostIssuesRequestOptions} options
 * @returns {YoRequest<Issue>}
 */
export function createPostIssuesRequest(options) {
  return {method: 'post', path: '/api/issues', query: options.query};
}

/**
 * @typedef {object} GetIssuesIssueRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetIssuesIssueRequestOptions} options
 * @returns {YoRequest<Issue>}
 */
export function createGetIssuesIssueRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesIssueRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostIssuesIssueRequestOptions} options
 * @returns {YoRequest<Issue>}
 */
export function createPostIssuesIssueRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteIssuesIssueRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteIssuesIssueRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteIssuesIssueRequest(options) {
  return {method: 'delete', path: interpolate('/api/issues/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetIssuesActivitiesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.activityItemId
 */

/**
 * @param {GetIssuesActivitiesRequestOptions} options
 * @returns {YoRequest<ActivityItem>}
 */
export function createGetIssuesActivitiesRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/activities', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesActivitiesPageRequestOptions
 * @property {object} [query]
 * @property {string} [query.categories]
 * @property {boolean} [query.reverse]
 * @property {string} [query.start]
 * @property {string} [query.end]
 * @property {string} [query.author]
 * @property {string} [query.cursor]
 * @property {string} [query.activityId]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.activityCursorPageId
 */

/**
 * @param {GetIssuesActivitiesPageRequestOptions} options
 * @returns {YoRequest<ActivityCursorPage>}
 */
export function createGetIssuesActivitiesPageRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/activitiesPage', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesAttachmentsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssuesAttachmentsRequestOptions} options
 * @returns {YoRequest<Array<IssueAttachment>>}
 */
export function createGetIssuesAttachmentsRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/attachments', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesAttachmentsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostIssuesAttachmentsRequestOptions} options
 * @returns {YoRequest<IssueAttachment>}
 */
export function createPostIssuesAttachmentsRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/attachments', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesAttachmentsIssueAttachmentRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueAttachmentId
 */

/**
 * @param {GetIssuesAttachmentsIssueAttachmentRequestOptions} options
 * @returns {YoRequest<IssueAttachment>}
 */
export function createGetIssuesAttachmentsIssueAttachmentRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/attachments/{issueAttachmentId}', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesAttachmentsIssueAttachmentRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueAttachmentId
 */

/**
 * @param {PostIssuesAttachmentsIssueAttachmentRequestOptions} options
 * @returns {YoRequest<IssueAttachment>}
 */
export function createPostIssuesAttachmentsIssueAttachmentRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/attachments/{issueAttachmentId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteIssuesAttachmentsIssueAttachmentRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueAttachmentId
 */

/**
 * @param {DeleteIssuesAttachmentsIssueAttachmentRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteIssuesAttachmentsIssueAttachmentRequest(options) {
  return {method: 'delete', path: interpolate('/api/issues/{id}/attachments/{issueAttachmentId}', options.path), query: null};
}

/**
 * @typedef {object} GetIssuesCommentsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssuesCommentsRequestOptions} options
 * @returns {YoRequest<Array<IssueComment>>}
 */
export function createGetIssuesCommentsRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/comments', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesCommentsRequestOptions
 * @property {object} [query]
 * @property {string} [query.draftId]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostIssuesCommentsRequestOptions} options
 * @returns {YoRequest<IssueComment>}
 */
export function createPostIssuesCommentsRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/comments', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesCommentsIssueCommentRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCommentId
 */

/**
 * @param {GetIssuesCommentsIssueCommentRequestOptions} options
 * @returns {YoRequest<IssueComment>}
 */
export function createGetIssuesCommentsIssueCommentRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/comments/{issueCommentId}', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesCommentsIssueCommentRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCommentId
 */

/**
 * @param {PostIssuesCommentsIssueCommentRequestOptions} options
 * @returns {YoRequest<IssueComment>}
 */
export function createPostIssuesCommentsIssueCommentRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/comments/{issueCommentId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteIssuesCommentsIssueCommentRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCommentId
 */

/**
 * @param {DeleteIssuesCommentsIssueCommentRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteIssuesCommentsIssueCommentRequest(options) {
  return {method: 'delete', path: interpolate('/api/issues/{id}/comments/{issueCommentId}', options.path), query: null};
}

/**
 * @typedef {object} GetIssuesCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssuesCustomFieldsRequestOptions} options
 * @returns {YoRequest<Array<IssueCustomField>>}
 */
export function createGetIssuesCustomFieldsRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/customFields', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesCustomFieldsIssueCustomFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCustomFieldId
 */

/**
 * @param {GetIssuesCustomFieldsIssueCustomFieldRequestOptions} options
 * @returns {YoRequest<IssueCustomField>}
 */
export function createGetIssuesCustomFieldsIssueCustomFieldRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/customFields/{issueCustomFieldId}', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesCustomFieldsIssueCustomFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCustomFieldId
 */

/**
 * @param {PostIssuesCustomFieldsIssueCustomFieldRequestOptions} options
 * @returns {YoRequest<IssueCustomField>}
 */
export function createPostIssuesCustomFieldsIssueCustomFieldRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/customFields/{issueCustomFieldId}', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesLinksRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssuesLinksRequestOptions} options
 * @returns {YoRequest<Array<IssueLink>>}
 */
export function createGetIssuesLinksRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/links', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesLinksIssueLinkRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueLinkId
 */

/**
 * @param {GetIssuesLinksIssueLinkRequestOptions} options
 * @returns {YoRequest<IssueLink>}
 */
export function createGetIssuesLinksIssueLinkRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/links/{issueLinkId}', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesLinksIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueLinkId
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssuesLinksIssuesRequestOptions} options
 * @returns {YoRequest<Array<Issue>>}
 */
export function createGetIssuesLinksIssuesRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/links/{issueLinkId}/issues', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesLinksIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueLinkId
 */

/**
 * @param {PostIssuesLinksIssuesRequestOptions} options
 * @returns {YoRequest<Issue>}
 */
export function createPostIssuesLinksIssuesRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/links/{issueLinkId}/issues', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteIssuesLinksIssuesIssueRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueLinkId
 * @property {string} path.issueId
 */

/**
 * @param {DeleteIssuesLinksIssuesIssueRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteIssuesLinksIssuesIssueRequest(options) {
  return {method: 'delete', path: interpolate('/api/issues/{id}/links/{issueLinkId}/issues/{issueId}', options.path), query: null};
}

/**
 * @typedef {object} GetIssuesProjectRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectId
 */

/**
 * @param {GetIssuesProjectRequestOptions} options
 * @returns {YoRequest<Project>}
 */
export function createGetIssuesProjectRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/project', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesProjectRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectId
 */

/**
 * @param {PostIssuesProjectRequestOptions} options
 * @returns {YoRequest<Project>}
 */
export function createPostIssuesProjectRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/project', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesTimeTrackingRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 */

/**
 * @param {GetIssuesTimeTrackingRequestOptions} options
 * @returns {YoRequest<IssueTimeTracker>}
 */
export function createGetIssuesTimeTrackingRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/timeTracking', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesTimeTrackingWorkItemsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetIssuesTimeTrackingWorkItemsRequestOptions} options
 * @returns {YoRequest<Array<IssueWorkItem>>}
 */
export function createGetIssuesTimeTrackingWorkItemsRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/timeTracking/workItems', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesTimeTrackingWorkItemsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 */

/**
 * @param {PostIssuesTimeTrackingWorkItemsRequestOptions} options
 * @returns {YoRequest<IssueWorkItem>}
 */
export function createPostIssuesTimeTrackingWorkItemsRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/timeTracking/workItems', options.path), query: options.query};
}

/**
 * @typedef {object} GetIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 * @property {string} path.issueWorkItemId
 */

/**
 * @param {GetIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions} options
 * @returns {YoRequest<IssueWorkItem>}
 */
export function createGetIssuesTimeTrackingWorkItemsIssueWorkItemRequest(options) {
  return {method: 'get', path: interpolate('/api/issues/{id}/timeTracking/workItems/{issueWorkItemId}', options.path), query: options.query};
}

/**
 * @typedef {object} PostIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 * @property {string} path.issueWorkItemId
 */

/**
 * @param {PostIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions} options
 * @returns {YoRequest<IssueWorkItem>}
 */
export function createPostIssuesTimeTrackingWorkItemsIssueWorkItemRequest(options) {
  return {method: 'post', path: interpolate('/api/issues/{id}/timeTracking/workItems/{issueWorkItemId}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 * @property {string} path.issueWorkItemId
 */

/**
 * @param {DeleteIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteIssuesTimeTrackingWorkItemsIssueWorkItemRequest(options) {
  return {method: 'delete', path: interpolate('/api/issues/{id}/timeTracking/workItems/{issueWorkItemId}', options.path), query: null};
}

/**
 * @typedef {object} GetSavedQueriesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetSavedQueriesRequestOptions} options
 * @returns {YoRequest<Array<SavedQuery>>}
 */
export function createGetSavedQueriesRequest(options) {
  return {method: 'get', path: '/api/savedQueries', query: options.query};
}

/**
 * @typedef {object} PostSavedQueriesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @param {PostSavedQueriesRequestOptions} options
 * @returns {YoRequest<SavedQuery>}
 */
export function createPostSavedQueriesRequest(options) {
  return {method: 'post', path: '/api/savedQueries', query: options.query};
}

/**
 * @typedef {object} GetSavedQueriesSavedQueryRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetSavedQueriesSavedQueryRequestOptions} options
 * @returns {YoRequest<SavedQuery>}
 */
export function createGetSavedQueriesSavedQueryRequest(options) {
  return {method: 'get', path: interpolate('/api/savedQueries/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} PostSavedQueriesSavedQueryRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {PostSavedQueriesSavedQueryRequestOptions} options
 * @returns {YoRequest<SavedQuery>}
 */
export function createPostSavedQueriesSavedQueryRequest(options) {
  return {method: 'post', path: interpolate('/api/savedQueries/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} DeleteSavedQueriesSavedQueryRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {DeleteSavedQueriesSavedQueryRequestOptions} options
 * @returns {YoRequest<object>}
 */
export function createDeleteSavedQueriesSavedQueryRequest(options) {
  return {method: 'delete', path: interpolate('/api/savedQueries/{id}', options.path), query: null};
}

/**
 * @typedef {object} GetUsersRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetUsersRequestOptions} options
 * @returns {YoRequest<Array<User>>}
 */
export function createGetUsersRequest(options) {
  return {method: 'get', path: '/api/users', query: options.query};
}

/**
 * @typedef {object} GetUsersUserRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetUsersUserRequestOptions} options
 * @returns {YoRequest<User>}
 */
export function createGetUsersUserRequest(options) {
  return {method: 'get', path: interpolate('/api/users/{id}', options.path), query: options.query};
}

/**
 * @typedef {object} GetUsersProfilesGeneralRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.generalUserProfileId
 */

/**
 * @param {GetUsersProfilesGeneralRequestOptions} options
 * @returns {YoRequest<GeneralUserProfile>}
 */
export function createGetUsersProfilesGeneralRequest(options) {
  return {method: 'get', path: interpolate('/api/users/{id}/profiles/general', options.path), query: options.query};
}

/**
 * @typedef {object} PostUsersProfilesGeneralRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.generalUserProfileId
 */

/**
 * @param {PostUsersProfilesGeneralRequestOptions} options
 * @returns {YoRequest<GeneralUserProfile>}
 */
export function createPostUsersProfilesGeneralRequest(options) {
  return {method: 'post', path: interpolate('/api/users/{id}/profiles/general', options.path), query: options.query};
}

/**
 * @typedef {object} GetUsersProfilesNotificationsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.notificationsUserProfileId
 */

/**
 * @param {GetUsersProfilesNotificationsRequestOptions} options
 * @returns {YoRequest<NotificationsUserProfile>}
 */
export function createGetUsersProfilesNotificationsRequest(options) {
  return {method: 'get', path: interpolate('/api/users/{id}/profiles/notifications', options.path), query: options.query};
}

/**
 * @typedef {object} PostUsersProfilesNotificationsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.notificationsUserProfileId
 */

/**
 * @param {PostUsersProfilesNotificationsRequestOptions} options
 * @returns {YoRequest<NotificationsUserProfile>}
 */
export function createPostUsersProfilesNotificationsRequest(options) {
  return {method: 'post', path: interpolate('/api/users/{id}/profiles/notifications', options.path), query: options.query};
}

/**
 * @typedef {object} GetUsersProfilesTimetrackingRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.timeTrackingUserProfileId
 */

/**
 * @param {GetUsersProfilesTimetrackingRequestOptions} options
 * @returns {YoRequest<TimeTrackingUserProfile>}
 */
export function createGetUsersProfilesTimetrackingRequest(options) {
  return {method: 'get', path: interpolate('/api/users/{id}/profiles/timetracking', options.path), query: options.query};
}

/**
 * @typedef {object} PostUsersProfilesTimetrackingRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.timeTrackingUserProfileId
 */

/**
 * @param {PostUsersProfilesTimetrackingRequestOptions} options
 * @returns {YoRequest<TimeTrackingUserProfile>}
 */
export function createPostUsersProfilesTimetrackingRequest(options) {
  return {method: 'post', path: interpolate('/api/users/{id}/profiles/timetracking', options.path), query: options.query};
}

/**
 * @typedef {object} GetUsersSavedQueriesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetUsersSavedQueriesRequestOptions} options
 * @returns {YoRequest<Array<SavedQuery>>}
 */
export function createGetUsersSavedQueriesRequest(options) {
  return {method: 'get', path: interpolate('/api/users/{id}/savedQueries', options.path), query: options.query};
}



/**
 * @typedef {object} GetUsersTagsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetUsersTagsRequestOptions} options
 * @returns {YoRequest<Array<IssueTag>>}
 */
export function createGetUsersTagsRequest(options) {
  return {method: 'get', path: interpolate('/api/users/{id}/tags', options.path), query: options.query};
}



/**
 * @typedef {object} GetUsersMeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetUsersMeRequestOptions} options
 * @returns {YoRequest<Me>}
 */
export function createGetUsersMeRequest(options) {
  return {method: 'get', path: interpolate('/api/users/me', options.path), query: options.query};
}

/**
 * @typedef {object} GetWorkItemsRequestOptions
 * @property {object} [query]
 * @property {string} [query.query]
 * @property {string} [query.startDate]
 * @property {string} [query.endDate]
 * @property {number} [query.start]
 * @property {number} [query.end]
 * @property {number} [query.createdStart]
 * @property {number} [query.createdEnd]
 * @property {number} [query.updatedStart]
 * @property {number} [query.updatedEnd]
 * @property {string} [query.author]
 * @property {string} [query.creator]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @param {GetWorkItemsRequestOptions} options
 * @returns {YoRequest<Array<IssueWorkItem>>}
 */
export function createGetWorkItemsRequest(options) {
  return {method: 'get', path: '/api/workItems', query: options.query};
}

/**
 * @typedef {object} GetWorkItemsIssueWorkItemRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @param {GetWorkItemsIssueWorkItemRequestOptions} options
 * @returns {YoRequest<IssueWorkItem>}
 */
export function createGetWorkItemsIssueWorkItemRequest(options) {
  return {method: 'get', path: interpolate('/api/workItems/{id}', options.path), query: options.query};
}