// AUTOGENERATED FILE DO NOT EDIT!
// This file was generated by script

/**
 * @typedef {object} GetActivitiesRequestOptions
 * @property {object} [query]
 * @property {string} [query.categories]
 * @property {boolean} [query.reverse]
 * @property {string} [query.start]
 * @property {string} [query.end]
 * @property {string} [query.author]
 * @property {string} [query.issueQuery]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} GetActivitiesActivityItemRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetActivitiesPageRequestOptions
 * @property {object} [query]
 * @property {string} [query.categories]
 * @property {boolean} [query.reverse]
 * @property {string} [query.start]
 * @property {string} [query.end]
 * @property {string} [query.author]
 * @property {string} [query.issueQuery]
 * @property {string} [query.cursor]
 * @property {string} [query.activityId]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesBuildRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesBuildRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesBuildBuildBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesEnumRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesEnumRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesEnumEnumBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesOwnedFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesOwnedFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesOwnedFieldOwnedBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesStateRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesStateRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesStateStateBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesUserRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesUserUserBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserAggregatedUsersRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */



/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserGroupsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesUserGroupsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserGroupsUserGroupRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.userGroupId
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesUserGroupsUserGroupRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.userGroupId
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserIndividualsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesUserIndividualsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesUserIndividualsUserRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.userId
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesUserIndividualsUserRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.userId
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesVersionRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesVersionRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsBundlesVersionVersionBundleRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAdminCustomFieldSettingsCustomFieldsCustomFieldRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsCustomFieldsFieldDefaultsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.customFieldDefaultsId
 */

/**
 * @typedef {object} PostAdminCustomFieldSettingsCustomFieldsFieldDefaultsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.customFieldDefaultsId
 */

/**
 * @typedef {object} GetAdminCustomFieldSettingsCustomFieldsInstancesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */



/**
 * @typedef {object} GetAdminCustomFieldSettingsTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */



/**
 * @typedef {object} GetAdminDatabaseBackupBackupsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} GetAdminDatabaseBackupBackupsBackupFileRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminDatabaseBackupSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminDatabaseBackupSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminDatabaseBackupSettingsBackupStatusRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.backupStatusId
 */

/**
 * @typedef {object} GetAdminGlobalSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminGlobalSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminGlobalSettingsAppearanceSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.appearanceSettingsId
 */

/**
 * @typedef {object} PostAdminGlobalSettingsAppearanceSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.appearanceSettingsId
 */

/**
 * @typedef {object} GetAdminGlobalSettingsLicenseRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.licenseId
 */

/**
 * @typedef {object} PostAdminGlobalSettingsLicenseRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.licenseId
 */

/**
 * @typedef {object} GetAdminGlobalSettingsLocaleSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.localeSettingsId
 */

/**
 * @typedef {object} PostAdminGlobalSettingsLocaleSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.localeSettingsId
 */

/**
 * @typedef {object} GetAdminGlobalSettingsNotificationSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.notificationSettingsId
 */

/**
 * @typedef {object} PostAdminGlobalSettingsNotificationSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.notificationSettingsId
 */

/**
 * @typedef {object} GetAdminGlobalSettingsRestSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.restCorsSettingsId
 */

/**
 * @typedef {object} PostAdminGlobalSettingsRestSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.restCorsSettingsId
 */

/**
 * @typedef {object} GetAdminGlobalSettingsSystemSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.systemSettingsId
 */

/**
 * @typedef {object} PostAdminGlobalSettingsSystemSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.systemSettingsId
 */

/**
 * @typedef {object} GetAdminProjectsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminProjectsRequestOptions
 * @property {object} [query]
 * @property {string} [query.template]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAdminProjectsProjectRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAdminProjectsProjectRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAdminProjectsProjectRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminProjectsCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectCustomFieldId
 */

/**
 * @typedef {object} PostAdminProjectsCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectCustomFieldId
 */

/**
 * @typedef {object} DeleteAdminProjectsCustomFieldsRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectCustomFieldId
 */

/**
 * @typedef {object} GetAdminProjectsIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminProjectsIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminProjectsIssuesIssueRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueId
 */

/**
 * @typedef {object} PostAdminProjectsIssuesIssueRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueId
 */

/**
 * @typedef {object} DeleteAdminProjectsIssuesIssueRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueId
 */

/**
 * @typedef {object} GetAdminProjectsTimeTrackingSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 */

/**
 * @typedef {object} PostAdminProjectsTimeTrackingSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 */

/**
 * @typedef {object} GetAdminProjectsTimeTrackingSettingsWorkItemTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminProjectsTimeTrackingSettingsWorkItemTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 */

/**
 * @typedef {object} GetAdminProjectsTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 * @property {string} path.workItemTypeId
 */

/**
 * @typedef {object} DeleteAdminProjectsTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectTimeTrackingSettingsId
 * @property {string} path.workItemTypeId
 */

/**
 * @typedef {object} GetAdminTimeTrackingSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminTimeTrackingSettingsWorkItemTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAdminTimeTrackingSettingsWorkItemTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workItemTypeId
 */

/**
 * @typedef {object} PostAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workItemTypeId
 */

/**
 * @typedef {object} DeleteAdminTimeTrackingSettingsWorkItemTypesWorkItemTypeRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workItemTypeId
 */

/**
 * @typedef {object} GetAdminTimeTrackingSettingsWorkTimeSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workTimeSettingsId
 */

/**
 * @typedef {object} PostAdminTimeTrackingSettingsWorkTimeSettingsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.workTimeSettingsId
 */

/**
 * @typedef {object} GetAgilesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAgilesRequestOptions
 * @property {object} [query]
 * @property {string} [query.template]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetAgilesAgileRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostAgilesAgileRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteAgilesAgileRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAgilesSprintsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostAgilesSprintsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetAgilesSprintsSprintRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.sprintId
 */

/**
 * @typedef {object} PostAgilesSprintsSprintRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.sprintId
 */

/**
 * @typedef {object} DeleteAgilesSprintsSprintRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.sprintId
 */





/**
 * @typedef {object} GetGroupsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} GetGroupsUserGroupRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetIssueLinkTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostIssueLinkTypesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetIssueLinkTypesIssueLinkTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostIssueLinkTypesIssueLinkTypeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteIssueLinkTypesIssueLinkTypeRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetIssueTagsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostIssueTagsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetIssueTagsIssueTagRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostIssueTagsIssueTagRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteIssueTagsIssueTagRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetIssueTagsIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */



/**
 * @typedef {object} GetIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.draftId]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetIssuesIssueRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostIssuesIssueRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteIssuesIssueRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetIssuesActivitiesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.activityItemId
 */

/**
 * @typedef {object} GetIssuesActivitiesPageRequestOptions
 * @property {object} [query]
 * @property {string} [query.categories]
 * @property {boolean} [query.reverse]
 * @property {string} [query.start]
 * @property {string} [query.end]
 * @property {string} [query.author]
 * @property {string} [query.cursor]
 * @property {string} [query.activityId]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.activityCursorPageId
 */

/**
 * @typedef {object} GetIssuesAttachmentsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostIssuesAttachmentsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetIssuesAttachmentsIssueAttachmentRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueAttachmentId
 */

/**
 * @typedef {object} PostIssuesAttachmentsIssueAttachmentRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueAttachmentId
 */

/**
 * @typedef {object} DeleteIssuesAttachmentsIssueAttachmentRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueAttachmentId
 */

/**
 * @typedef {object} GetIssuesCommentsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostIssuesCommentsRequestOptions
 * @property {object} [query]
 * @property {string} [query.draftId]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetIssuesCommentsIssueCommentRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCommentId
 */

/**
 * @typedef {object} PostIssuesCommentsIssueCommentRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCommentId
 */

/**
 * @typedef {object} DeleteIssuesCommentsIssueCommentRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCommentId
 */

/**
 * @typedef {object} GetIssuesCustomFieldsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} GetIssuesCustomFieldsIssueCustomFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCustomFieldId
 */

/**
 * @typedef {object} PostIssuesCustomFieldsIssueCustomFieldRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueCustomFieldId
 */

/**
 * @typedef {object} GetIssuesLinksRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} GetIssuesLinksIssueLinkRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueLinkId
 */

/**
 * @typedef {object} GetIssuesLinksIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueLinkId
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostIssuesLinksIssuesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueLinkId
 */

/**
 * @typedef {object} DeleteIssuesLinksIssuesIssueRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueLinkId
 * @property {string} path.issueId
 */

/**
 * @typedef {object} GetIssuesProjectRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectId
 */

/**
 * @typedef {object} PostIssuesProjectRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.projectId
 */

/**
 * @typedef {object} GetIssuesTimeTrackingRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 */

/**
 * @typedef {object} GetIssuesTimeTrackingWorkItemsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostIssuesTimeTrackingWorkItemsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 */

/**
 * @typedef {object} GetIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 * @property {string} path.issueWorkItemId
 */

/**
 * @typedef {object} PostIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 * @property {string} path.issueWorkItemId
 */

/**
 * @typedef {object} DeleteIssuesTimeTrackingWorkItemsIssueWorkItemRequestOptions
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.issueTimeTrackingId
 * @property {string} path.issueWorkItemId
 */

/**
 * @typedef {object} GetSavedQueriesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} PostSavedQueriesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 */

/**
 * @typedef {object} GetSavedQueriesSavedQueryRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} PostSavedQueriesSavedQueryRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} DeleteSavedQueriesSavedQueryRequestOptions
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetUsersRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} GetUsersUserRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetUsersProfilesGeneralRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.generalUserProfileId
 */

/**
 * @typedef {object} PostUsersProfilesGeneralRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.generalUserProfileId
 */

/**
 * @typedef {object} GetUsersProfilesNotificationsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.notificationsUserProfileId
 */

/**
 * @typedef {object} PostUsersProfilesNotificationsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.notificationsUserProfileId
 */

/**
 * @typedef {object} GetUsersProfilesTimetrackingRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.timeTrackingUserProfileId
 */

/**
 * @typedef {object} PostUsersProfilesTimetrackingRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {string} path.timeTrackingUserProfileId
 */

/**
 * @typedef {object} GetUsersSavedQueriesRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */



/**
 * @typedef {object} GetUsersTagsRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */



/**
 * @typedef {object} GetUsersMeRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */

/**
 * @typedef {object} GetWorkItemsRequestOptions
 * @property {object} [query]
 * @property {string} [query.query]
 * @property {string} [query.startDate]
 * @property {string} [query.endDate]
 * @property {number} [query.start]
 * @property {number} [query.end]
 * @property {number} [query.createdStart]
 * @property {number} [query.createdEnd]
 * @property {number} [query.updatedStart]
 * @property {number} [query.updatedEnd]
 * @property {string} [query.author]
 * @property {string} [query.creator]
 * @property {string} [query.fields]
 * @property {number} [query.$skip]
 * @property {number} [query.$top]
 */

/**
 * @typedef {object} GetWorkItemsIssueWorkItemRequestOptions
 * @property {object} [query]
 * @property {string} [query.fields]
 * @property {object} path
 * @property {string} path.id
 */