const { resourceFromPath } = require('./resourceGenerator');
const { promisify } = require('util');
const { resolve } = require('path');
const { downloadSchema } = require('./schema');
const { jsdocForComponent } = require('./jsdoc');

function main() {
  const codegenComment =
    '// AUTOGENERATED FILE DO NOT EDIT!\n' +
    '// This file was generated by script\n' +
    '\n'
  ;

  downloadSchema('https://youtrack.jetbrains.com').then((data) => {
    generateComponentsJsDoc(data);
    generateResources(data);
  });

  function generateComponentsJsDoc(data) {
    return generateDoc(data.components.schemas, jsdocForComponent, '../lib/entities.js');
  }

  function generateResources(data) {
    return generateDoc(data.paths, resourceFromPath, '../lib/resources.js');
  }

  function generateDoc(entities, generator, path) {
    const docPath = resolve(__dirname, path);
    const doc = Object.keys(entities)
      .map((key) => resourceFromPath(key, entities[key])).join('\n\n');
    return promisify(require('fs').writeFile)(docPath, codegenComment + doc);
  }
}

main();